// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jkafka"
	mock "github.com/stretchr/testify/mock"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type Store
func (_mock *Store) Insert(ctx context.Context, topic string, id string, eventType jkafka.Type, state string) error {
	ret := _mock.Called(ctx, topic, id, eventType, state)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jkafka.Type, string) error); ok {
		r0 = returnFunc(ctx, topic, id, eventType, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type Store_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - id string
//   - eventType jkafka.Type
//   - state string
func (_e *Store_Expecter) Insert(ctx any, topic any, id any, eventType any, state any) *Store_Insert_Call {
	return &Store_Insert_Call{Call: _e.mock.On("Insert", ctx, topic, id, eventType, state)}
}

func (_c *Store_Insert_Call) Run(run func(ctx context.Context, topic string, id string, eventType jkafka.Type, state string)) *Store_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 jkafka.Type
		if args[3] != nil {
			arg3 = args[3].(jkafka.Type)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Store_Insert_Call) Return(err error) *Store_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_Insert_Call) RunAndReturn(run func(ctx context.Context, topic string, id string, eventType jkafka.Type, state string) error) *Store_Insert_Call {
	_c.Call.Return(run)
	return _c
}
