// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jkafka/outbox/types"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkerStore creates a new instance of WorkerStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkerStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkerStore {
	mock := &WorkerStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkerStore is an autogenerated mock type for the WorkerStore type
type WorkerStore struct {
	mock.Mock
}

type WorkerStore_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkerStore) EXPECT() *WorkerStore_Expecter {
	return &WorkerStore_Expecter{mock: &_m.Mock}
}

// GetNextEvent provides a mock function for the type WorkerStore
func (_mock *WorkerStore) GetNextEvent(ctx context.Context) (types.StoredEvent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNextEvent")
	}

	var r0 types.StoredEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (types.StoredEvent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) types.StoredEvent); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(types.StoredEvent)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkerStore_GetNextEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextEvent'
type WorkerStore_GetNextEvent_Call struct {
	*mock.Call
}

// GetNextEvent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *WorkerStore_Expecter) GetNextEvent(ctx any) *WorkerStore_GetNextEvent_Call {
	return &WorkerStore_GetNextEvent_Call{Call: _e.mock.On("GetNextEvent", ctx)}
}

func (_c *WorkerStore_GetNextEvent_Call) Run(run func(ctx context.Context)) *WorkerStore_GetNextEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WorkerStore_GetNextEvent_Call) Return(storedEvent types.StoredEvent, err error) *WorkerStore_GetNextEvent_Call {
	_c.Call.Return(storedEvent, err)
	return _c
}

func (_c *WorkerStore_GetNextEvent_Call) RunAndReturn(run func(ctx context.Context) (types.StoredEvent, error)) *WorkerStore_GetNextEvent_Call {
	_c.Call.Return(run)
	return _c
}

// SetEventSent provides a mock function for the type WorkerStore
func (_mock *WorkerStore) SetEventSent(ctx context.Context, sentEventID uuid.UUID) error {
	ret := _mock.Called(ctx, sentEventID)

	if len(ret) == 0 {
		panic("no return value specified for SetEventSent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sentEventID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkerStore_SetEventSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEventSent'
type WorkerStore_SetEventSent_Call struct {
	*mock.Call
}

// SetEventSent is a helper method to define mock.On call
//   - ctx context.Context
//   - sentEventID uuid.UUID
func (_e *WorkerStore_Expecter) SetEventSent(ctx any, sentEventID any) *WorkerStore_SetEventSent_Call {
	return &WorkerStore_SetEventSent_Call{Call: _e.mock.On("SetEventSent", ctx, sentEventID)}
}

func (_c *WorkerStore_SetEventSent_Call) Run(run func(ctx context.Context, sentEventID uuid.UUID)) *WorkerStore_SetEventSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WorkerStore_SetEventSent_Call) Return(err error) *WorkerStore_SetEventSent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkerStore_SetEventSent_Call) RunAndReturn(run func(ctx context.Context, sentEventID uuid.UUID) error) *WorkerStore_SetEventSent_Call {
	_c.Call.Return(run)
	return _c
}
