// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewRunnerTx creates a new instance of RunnerTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunnerTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *RunnerTx {
	mock := &RunnerTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RunnerTx is an autogenerated mock type for the RunnerTx type
type RunnerTx struct {
	mock.Mock
}

type RunnerTx_Expecter struct {
	mock *mock.Mock
}

func (_m *RunnerTx) EXPECT() *RunnerTx_Expecter {
	return &RunnerTx_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type RunnerTx
func (_mock *RunnerTx) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RunnerTx_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type RunnerTx_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *RunnerTx_Expecter) Commit() *RunnerTx_Commit_Call {
	return &RunnerTx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *RunnerTx_Commit_Call) Run(run func()) *RunnerTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RunnerTx_Commit_Call) Return(err error) *RunnerTx_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RunnerTx_Commit_Call) RunAndReturn(run func() error) *RunnerTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type RunnerTx
func (_mock *RunnerTx) Exec(query string, args ...any) (sql.Result, error) {
	var _ca []any
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (sql.Result, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) sql.Result); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RunnerTx_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type RunnerTx_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *RunnerTx_Expecter) Exec(query any, args ...any) *RunnerTx_Exec_Call {
	return &RunnerTx_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{query}, args...)...)}
}

func (_c *RunnerTx_Exec_Call) Run(run func(query string, args ...any)) *RunnerTx_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RunnerTx_Exec_Call) Return(result sql.Result, err error) *RunnerTx_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *RunnerTx_Exec_Call) RunAndReturn(run func(query string, args ...any) (sql.Result, error)) *RunnerTx_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type RunnerTx
func (_mock *RunnerTx) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RunnerTx_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type RunnerTx_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *RunnerTx_Expecter) ExecContext(ctx any, query any, args ...any) *RunnerTx_ExecContext_Call {
	return &RunnerTx_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]any{ctx, query}, args...)...)}
}

func (_c *RunnerTx_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *RunnerTx_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RunnerTx_ExecContext_Call) Return(result sql.Result, err error) *RunnerTx_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *RunnerTx_ExecContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sql.Result, error)) *RunnerTx_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type RunnerTx
func (_mock *RunnerTx) Prepare(query string) (*sql.Stmt, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RunnerTx_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type RunnerTx_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *RunnerTx_Expecter) Prepare(query any) *RunnerTx_Prepare_Call {
	return &RunnerTx_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *RunnerTx_Prepare_Call) Run(run func(query string)) *RunnerTx_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RunnerTx_Prepare_Call) Return(stmt *sql.Stmt, err error) *RunnerTx_Prepare_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *RunnerTx_Prepare_Call) RunAndReturn(run func(query string) (*sql.Stmt, error)) *RunnerTx_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function for the type RunnerTx
func (_mock *RunnerTx) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RunnerTx_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type RunnerTx_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *RunnerTx_Expecter) PrepareContext(ctx any, query any) *RunnerTx_PrepareContext_Call {
	return &RunnerTx_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *RunnerTx_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *RunnerTx_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RunnerTx_PrepareContext_Call) Return(stmt *sql.Stmt, err error) *RunnerTx_PrepareContext_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *RunnerTx_PrepareContext_Call) RunAndReturn(run func(ctx context.Context, query string) (*sql.Stmt, error)) *RunnerTx_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type RunnerTx
func (_mock *RunnerTx) Query(query string, args ...any) (*sql.Rows, error) {
	var _ca []any
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Rows); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RunnerTx_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type RunnerTx_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *RunnerTx_Expecter) Query(query any, args ...any) *RunnerTx_Query_Call {
	return &RunnerTx_Query_Call{Call: _e.mock.On("Query",
		append([]any{query}, args...)...)}
}

func (_c *RunnerTx_Query_Call) Run(run func(query string, args ...any)) *RunnerTx_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RunnerTx_Query_Call) Return(rows *sql.Rows, err error) *RunnerTx_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *RunnerTx_Query_Call) RunAndReturn(run func(query string, args ...any) (*sql.Rows, error)) *RunnerTx_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type RunnerTx
func (_mock *RunnerTx) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RunnerTx_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type RunnerTx_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *RunnerTx_Expecter) QueryContext(ctx any, query any, args ...any) *RunnerTx_QueryContext_Call {
	return &RunnerTx_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]any{ctx, query}, args...)...)}
}

func (_c *RunnerTx_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *RunnerTx_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RunnerTx_QueryContext_Call) Return(rows *sql.Rows, err error) *RunnerTx_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *RunnerTx_QueryContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sql.Rows, error)) *RunnerTx_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type RunnerTx
func (_mock *RunnerTx) QueryRow(query string, args ...any) *sql.Row {
	var _ca []any
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Row); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// RunnerTx_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type RunnerTx_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *RunnerTx_Expecter) QueryRow(query any, args ...any) *RunnerTx_QueryRow_Call {
	return &RunnerTx_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{query}, args...)...)}
}

func (_c *RunnerTx_QueryRow_Call) Run(run func(query string, args ...any)) *RunnerTx_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RunnerTx_QueryRow_Call) Return(row *sql.Row) *RunnerTx_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *RunnerTx_QueryRow_Call) RunAndReturn(run func(query string, args ...any) *sql.Row) *RunnerTx_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function for the type RunnerTx
func (_mock *RunnerTx) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// RunnerTx_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type RunnerTx_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *RunnerTx_Expecter) QueryRowContext(ctx any, query any, args ...any) *RunnerTx_QueryRowContext_Call {
	return &RunnerTx_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]any{ctx, query}, args...)...)}
}

func (_c *RunnerTx_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *RunnerTx_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RunnerTx_QueryRowContext_Call) Return(row *sql.Row) *RunnerTx_QueryRowContext_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *RunnerTx_QueryRowContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) *sql.Row) *RunnerTx_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type RunnerTx
func (_mock *RunnerTx) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RunnerTx_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type RunnerTx_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *RunnerTx_Expecter) Rollback() *RunnerTx_Rollback_Call {
	return &RunnerTx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *RunnerTx_Rollback_Call) Run(run func()) *RunnerTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RunnerTx_Rollback_Call) Return(err error) *RunnerTx_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RunnerTx_Rollback_Call) RunAndReturn(run func() error) *RunnerTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
