// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewRunner creates a new instance of Runner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Runner {
	mock := &Runner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

type Runner_Expecter struct {
	mock *mock.Mock
}

func (_m *Runner) EXPECT() *Runner_Expecter {
	return &Runner_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type Runner
func (_mock *Runner) Exec(query string, args ...any) (sql.Result, error) {
	var _ca []any
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (sql.Result, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) sql.Result); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type Runner_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *Runner_Expecter) Exec(query any, args ...any) *Runner_Exec_Call {
	return &Runner_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{query}, args...)...)}
}

func (_c *Runner_Exec_Call) Run(run func(query string, args ...any)) *Runner_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Runner_Exec_Call) Return(result sql.Result, err error) *Runner_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Runner_Exec_Call) RunAndReturn(run func(query string, args ...any) (sql.Result, error)) *Runner_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type Runner
func (_mock *Runner) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (sql.Result, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) sql.Result); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type Runner_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Runner_Expecter) ExecContext(ctx any, query any, args ...any) *Runner_ExecContext_Call {
	return &Runner_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]any{ctx, query}, args...)...)}
}

func (_c *Runner_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *Runner_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Runner_ExecContext_Call) Return(result sql.Result, err error) *Runner_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *Runner_ExecContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (sql.Result, error)) *Runner_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type Runner
func (_mock *Runner) Prepare(query string) (*sql.Stmt, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*sql.Stmt, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *sql.Stmt); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type Runner_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *Runner_Expecter) Prepare(query any) *Runner_Prepare_Call {
	return &Runner_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *Runner_Prepare_Call) Run(run func(query string)) *Runner_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Runner_Prepare_Call) Return(stmt *sql.Stmt, err error) *Runner_Prepare_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *Runner_Prepare_Call) RunAndReturn(run func(query string) (*sql.Stmt, error)) *Runner_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function for the type Runner
func (_mock *Runner) PrepareContext(ctx context.Context, query string) (*sql.Stmt, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type Runner_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *Runner_Expecter) PrepareContext(ctx any, query any) *Runner_PrepareContext_Call {
	return &Runner_PrepareContext_Call{Call: _e.mock.On("PrepareContext", ctx, query)}
}

func (_c *Runner_PrepareContext_Call) Run(run func(ctx context.Context, query string)) *Runner_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Runner_PrepareContext_Call) Return(stmt *sql.Stmt, err error) *Runner_PrepareContext_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *Runner_PrepareContext_Call) RunAndReturn(run func(ctx context.Context, query string) (*sql.Stmt, error)) *Runner_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type Runner
func (_mock *Runner) Query(query string, args ...any) (*sql.Rows, error) {
	var _ca []any
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Rows); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Runner_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *Runner_Expecter) Query(query any, args ...any) *Runner_Query_Call {
	return &Runner_Query_Call{Call: _e.mock.On("Query",
		append([]any{query}, args...)...)}
}

func (_c *Runner_Query_Call) Run(run func(query string, args ...any)) *Runner_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Runner_Query_Call) Return(rows *sql.Rows, err error) *Runner_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *Runner_Query_Call) RunAndReturn(run func(query string, args ...any) (*sql.Rows, error)) *Runner_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type Runner
func (_mock *Runner) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (*sql.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Runner_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type Runner_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Runner_Expecter) QueryContext(ctx any, query any, args ...any) *Runner_QueryContext_Call {
	return &Runner_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]any{ctx, query}, args...)...)}
}

func (_c *Runner_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *Runner_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Runner_QueryContext_Call) Return(rows *sql.Rows, err error) *Runner_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *Runner_QueryContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) (*sql.Rows, error)) *Runner_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type Runner
func (_mock *Runner) QueryRow(query string, args ...any) *sql.Row {
	var _ca []any
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *sql.Row); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// Runner_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type Runner_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...any
func (_e *Runner_Expecter) QueryRow(query any, args ...any) *Runner_QueryRow_Call {
	return &Runner_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{query}, args...)...)}
}

func (_c *Runner_QueryRow_Call) Run(run func(query string, args ...any)) *Runner_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Runner_QueryRow_Call) Return(row *sql.Row) *Runner_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *Runner_QueryRow_Call) RunAndReturn(run func(query string, args ...any) *sql.Row) *Runner_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function for the type Runner
func (_mock *Runner) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	var _ca []any
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) *sql.Row); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// Runner_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type Runner_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *Runner_Expecter) QueryRowContext(ctx any, query any, args ...any) *Runner_QueryRowContext_Call {
	return &Runner_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]any{ctx, query}, args...)...)}
}

func (_c *Runner_QueryRowContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *Runner_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Runner_QueryRowContext_Call) Return(row *sql.Row) *Runner_QueryRowContext_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *Runner_QueryRowContext_Call) RunAndReturn(run func(ctx context.Context, query string, args ...any) *sql.Row) *Runner_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}
