// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iter"

	"github.com/Freelance-launchpad/backend-interview/common/jdb"
	"github.com/Freelance-launchpad/backend-interview/common/jentity"
	"github.com/Freelance-launchpad/backend-interview/services/users/pkg"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CreateJobContract provides a mock function for the type Client
func (_mock *Client) CreateJobContract(ctx context.Context, offerID uuid.UUID, contract pkg.Contract, address pkg.Address) (uuid.UUID, error) {
	ret := _mock.Called(ctx, offerID, contract, address)

	if len(ret) == 0 {
		panic("no return value specified for CreateJobContract")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.Contract, pkg.Address) (uuid.UUID, error)); ok {
		return returnFunc(ctx, offerID, contract, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.Contract, pkg.Address) uuid.UUID); ok {
		r0 = returnFunc(ctx, offerID, contract, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, pkg.Contract, pkg.Address) error); ok {
		r1 = returnFunc(ctx, offerID, contract, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_CreateJobContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJobContract'
type Client_CreateJobContract_Call struct {
	*mock.Call
}

// CreateJobContract is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - contract pkg.Contract
//   - address pkg.Address
func (_e *Client_Expecter) CreateJobContract(ctx any, offerID any, contract any, address any) *Client_CreateJobContract_Call {
	return &Client_CreateJobContract_Call{Call: _e.mock.On("CreateJobContract", ctx, offerID, contract, address)}
}

func (_c *Client_CreateJobContract_Call) Run(run func(ctx context.Context, offerID uuid.UUID, contract pkg.Contract, address pkg.Address)) *Client_CreateJobContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 pkg.Contract
		if args[2] != nil {
			arg2 = args[2].(pkg.Contract)
		}
		var arg3 pkg.Address
		if args[3] != nil {
			arg3 = args[3].(pkg.Address)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_CreateJobContract_Call) Return(uUID uuid.UUID, err error) *Client_CreateJobContract_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Client_CreateJobContract_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, contract pkg.Contract, address pkg.Address) (uuid.UUID, error)) *Client_CreateJobContract_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCRMData provides a mock function for the type Client
func (_mock *Client) DeleteCRMData(ctx context.Context, crmContactID string) error {
	ret := _mock.Called(ctx, crmContactID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCRMData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, crmContactID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteCRMData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCRMData'
type Client_DeleteCRMData_Call struct {
	*mock.Call
}

// DeleteCRMData is a helper method to define mock.On call
//   - ctx context.Context
//   - crmContactID string
func (_e *Client_Expecter) DeleteCRMData(ctx any, crmContactID any) *Client_DeleteCRMData_Call {
	return &Client_DeleteCRMData_Call{Call: _e.mock.On("DeleteCRMData", ctx, crmContactID)}
}

func (_c *Client_DeleteCRMData_Call) Run(run func(ctx context.Context, crmContactID string)) *Client_DeleteCRMData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteCRMData_Call) Return(err error) *Client_DeleteCRMData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteCRMData_Call) RunAndReturn(run func(ctx context.Context, crmContactID string) error) *Client_DeleteCRMData_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type Client
func (_mock *Client) DeleteFile(ctx context.Context, fileID uuid.UUID) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type Client_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID uuid.UUID
func (_e *Client_Expecter) DeleteFile(ctx any, fileID any) *Client_DeleteFile_Call {
	return &Client_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, fileID)}
}

func (_c *Client_DeleteFile_Call) Run(run func(ctx context.Context, fileID uuid.UUID)) *Client_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteFile_Call) Return(err error) *Client_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, fileID uuid.UUID) error) *Client_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJobContract provides a mock function for the type Client
func (_mock *Client) DeleteJobContract(ctx context.Context, offerID uuid.UUID) error {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJobContract")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteJobContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJobContract'
type Client_DeleteJobContract_Call struct {
	*mock.Call
}

// DeleteJobContract is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) DeleteJobContract(ctx any, offerID any) *Client_DeleteJobContract_Call {
	return &Client_DeleteJobContract_Call{Call: _e.mock.On("DeleteJobContract", ctx, offerID)}
}

func (_c *Client_DeleteJobContract_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_DeleteJobContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteJobContract_Call) Return(err error) *Client_DeleteJobContract_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteJobContract_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) error) *Client_DeleteJobContract_Call {
	_c.Call.Return(run)
	return _c
}

// DisableOffer provides a mock function for the type Client
func (_mock *Client) DisableOffer(ctx context.Context, offerID uuid.UUID) error {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for DisableOffer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DisableOffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableOffer'
type Client_DisableOffer_Call struct {
	*mock.Call
}

// DisableOffer is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) DisableOffer(ctx any, offerID any) *Client_DisableOffer_Call {
	return &Client_DisableOffer_Call{Call: _e.mock.On("DisableOffer", ctx, offerID)}
}

func (_c *Client_DisableOffer_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_DisableOffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DisableOffer_Call) Return(err error) *Client_DisableOffer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DisableOffer_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) error) *Client_DisableOffer_Call {
	_c.Call.Return(run)
	return _c
}

// EnableOffer provides a mock function for the type Client
func (_mock *Client) EnableOffer(ctx context.Context, offerID uuid.UUID) error {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for EnableOffer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_EnableOffer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableOffer'
type Client_EnableOffer_Call struct {
	*mock.Call
}

// EnableOffer is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) EnableOffer(ctx any, offerID any) *Client_EnableOffer_Call {
	return &Client_EnableOffer_Call{Call: _e.mock.On("EnableOffer", ctx, offerID)}
}

func (_c *Client_EnableOffer_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_EnableOffer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_EnableOffer_Call) Return(err error) *Client_EnableOffer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_EnableOffer_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) error) *Client_EnableOffer_Call {
	_c.Call.Return(run)
	return _c
}

// GetChurnByOfferID provides a mock function for the type Client
func (_mock *Client) GetChurnByOfferID(ctx context.Context, offerID uuid.UUID) (pkg.Churn, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetChurnByOfferID")
	}

	var r0 pkg.Churn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.Churn, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.Churn); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.Churn)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetChurnByOfferID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChurnByOfferID'
type Client_GetChurnByOfferID_Call struct {
	*mock.Call
}

// GetChurnByOfferID is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetChurnByOfferID(ctx any, offerID any) *Client_GetChurnByOfferID_Call {
	return &Client_GetChurnByOfferID_Call{Call: _e.mock.On("GetChurnByOfferID", ctx, offerID)}
}

func (_c *Client_GetChurnByOfferID_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetChurnByOfferID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetChurnByOfferID_Call) Return(churn pkg.Churn, err error) *Client_GetChurnByOfferID_Call {
	_c.Call.Return(churn, err)
	return _c
}

func (_c *Client_GetChurnByOfferID_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.Churn, error)) *Client_GetChurnByOfferID_Call {
	_c.Call.Return(run)
	return _c
}

// GetHRIDs provides a mock function for the type Client
func (_mock *Client) GetHRIDs(ctx context.Context, ssn string, entity *jentity.Entity) ([]string, error) {
	ret := _mock.Called(ctx, ssn, entity)

	if len(ret) == 0 {
		panic("no return value specified for GetHRIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *jentity.Entity) ([]string, error)); ok {
		return returnFunc(ctx, ssn, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *jentity.Entity) []string); ok {
		r0 = returnFunc(ctx, ssn, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *jentity.Entity) error); ok {
		r1 = returnFunc(ctx, ssn, entity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetHRIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHRIDs'
type Client_GetHRIDs_Call struct {
	*mock.Call
}

// GetHRIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ssn string
//   - entity *jentity.Entity
func (_e *Client_Expecter) GetHRIDs(ctx any, ssn any, entity any) *Client_GetHRIDs_Call {
	return &Client_GetHRIDs_Call{Call: _e.mock.On("GetHRIDs", ctx, ssn, entity)}
}

func (_c *Client_GetHRIDs_Call) Run(run func(ctx context.Context, ssn string, entity *jentity.Entity)) *Client_GetHRIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *jentity.Entity
		if args[2] != nil {
			arg2 = args[2].(*jentity.Entity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetHRIDs_Call) Return(strings []string, err error) *Client_GetHRIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *Client_GetHRIDs_Call) RunAndReturn(run func(ctx context.Context, ssn string, entity *jentity.Entity) ([]string, error)) *Client_GetHRIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetHRInfo provides a mock function for the type Client
func (_mock *Client) GetHRInfo(ctx context.Context, hrID string) (pkg.HRInfo, error) {
	ret := _mock.Called(ctx, hrID)

	if len(ret) == 0 {
		panic("no return value specified for GetHRInfo")
	}

	var r0 pkg.HRInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (pkg.HRInfo, error)); ok {
		return returnFunc(ctx, hrID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) pkg.HRInfo); ok {
		r0 = returnFunc(ctx, hrID)
	} else {
		r0 = ret.Get(0).(pkg.HRInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hrID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetHRInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHRInfo'
type Client_GetHRInfo_Call struct {
	*mock.Call
}

// GetHRInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - hrID string
func (_e *Client_Expecter) GetHRInfo(ctx any, hrID any) *Client_GetHRInfo_Call {
	return &Client_GetHRInfo_Call{Call: _e.mock.On("GetHRInfo", ctx, hrID)}
}

func (_c *Client_GetHRInfo_Call) Run(run func(ctx context.Context, hrID string)) *Client_GetHRInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetHRInfo_Call) Return(hRInfo pkg.HRInfo, err error) *Client_GetHRInfo_Call {
	_c.Call.Return(hRInfo, err)
	return _c
}

func (_c *Client_GetHRInfo_Call) RunAndReturn(run func(ctx context.Context, hrID string) (pkg.HRInfo, error)) *Client_GetHRInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetLifeOfferAddress provides a mock function for the type Client
func (_mock *Client) GetLifeOfferAddress(ctx context.Context, offerID uuid.UUID) (pkg.Address, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetLifeOfferAddress")
	}

	var r0 pkg.Address
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.Address, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.Address); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.Address)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetLifeOfferAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLifeOfferAddress'
type Client_GetLifeOfferAddress_Call struct {
	*mock.Call
}

// GetLifeOfferAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetLifeOfferAddress(ctx any, offerID any) *Client_GetLifeOfferAddress_Call {
	return &Client_GetLifeOfferAddress_Call{Call: _e.mock.On("GetLifeOfferAddress", ctx, offerID)}
}

func (_c *Client_GetLifeOfferAddress_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetLifeOfferAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetLifeOfferAddress_Call) Return(address pkg.Address, err error) *Client_GetLifeOfferAddress_Call {
	_c.Call.Return(address, err)
	return _c
}

func (_c *Client_GetLifeOfferAddress_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.Address, error)) *Client_GetLifeOfferAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetLifeUserInfo provides a mock function for the type Client
func (_mock *Client) GetLifeUserInfo(ctx context.Context, offerID uuid.UUID) (pkg.LifeUserInfo, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetLifeUserInfo")
	}

	var r0 pkg.LifeUserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.LifeUserInfo, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.LifeUserInfo); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.LifeUserInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetLifeUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLifeUserInfo'
type Client_GetLifeUserInfo_Call struct {
	*mock.Call
}

// GetLifeUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetLifeUserInfo(ctx any, offerID any) *Client_GetLifeUserInfo_Call {
	return &Client_GetLifeUserInfo_Call{Call: _e.mock.On("GetLifeUserInfo", ctx, offerID)}
}

func (_c *Client_GetLifeUserInfo_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetLifeUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetLifeUserInfo_Call) Return(lifeUserInfo pkg.LifeUserInfo, err error) *Client_GetLifeUserInfo_Call {
	_c.Call.Return(lifeUserInfo, err)
	return _c
}

func (_c *Client_GetLifeUserInfo_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.LifeUserInfo, error)) *Client_GetLifeUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfferByID provides a mock function for the type Client
func (_mock *Client) GetOfferByID(ctx context.Context, id uuid.UUID) (pkg.Offer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOfferByID")
	}

	var r0 pkg.Offer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.Offer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.Offer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(pkg.Offer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetOfferByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfferByID'
type Client_GetOfferByID_Call struct {
	*mock.Call
}

// GetOfferByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Client_Expecter) GetOfferByID(ctx any, id any) *Client_GetOfferByID_Call {
	return &Client_GetOfferByID_Call{Call: _e.mock.On("GetOfferByID", ctx, id)}
}

func (_c *Client_GetOfferByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Client_GetOfferByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetOfferByID_Call) Return(offer pkg.Offer, err error) *Client_GetOfferByID_Call {
	_c.Call.Return(offer, err)
	return _c
}

func (_c *Client_GetOfferByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (pkg.Offer, error)) *Client_GetOfferByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfferInfo provides a mock function for the type Client
func (_mock *Client) GetOfferInfo(ctx context.Context, offerID uuid.UUID) (pkg.OfferInfo, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetOfferInfo")
	}

	var r0 pkg.OfferInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.OfferInfo, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.OfferInfo); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.OfferInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetOfferInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfferInfo'
type Client_GetOfferInfo_Call struct {
	*mock.Call
}

// GetOfferInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetOfferInfo(ctx any, offerID any) *Client_GetOfferInfo_Call {
	return &Client_GetOfferInfo_Call{Call: _e.mock.On("GetOfferInfo", ctx, offerID)}
}

func (_c *Client_GetOfferInfo_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetOfferInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetOfferInfo_Call) Return(offerInfo pkg.OfferInfo, err error) *Client_GetOfferInfo_Call {
	_c.Call.Return(offerInfo, err)
	return _c
}

func (_c *Client_GetOfferInfo_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.OfferInfo, error)) *Client_GetOfferInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfferJobContract provides a mock function for the type Client
func (_mock *Client) GetOfferJobContract(ctx context.Context, id uuid.UUID) (pkg.Contract, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOfferJobContract")
	}

	var r0 pkg.Contract
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.Contract, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.Contract); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(pkg.Contract)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetOfferJobContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfferJobContract'
type Client_GetOfferJobContract_Call struct {
	*mock.Call
}

// GetOfferJobContract is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *Client_Expecter) GetOfferJobContract(ctx any, id any) *Client_GetOfferJobContract_Call {
	return &Client_GetOfferJobContract_Call{Call: _e.mock.On("GetOfferJobContract", ctx, id)}
}

func (_c *Client_GetOfferJobContract_Call) Run(run func(ctx context.Context, id uuid.UUID)) *Client_GetOfferJobContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetOfferJobContract_Call) Return(contract pkg.Contract, err error) *Client_GetOfferJobContract_Call {
	_c.Call.Return(contract, err)
	return _c
}

func (_c *Client_GetOfferJobContract_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (pkg.Contract, error)) *Client_GetOfferJobContract_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfferLegalInfo provides a mock function for the type Client
func (_mock *Client) GetOfferLegalInfo(ctx context.Context, offerID uuid.UUID) (pkg.LegalInfo, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetOfferLegalInfo")
	}

	var r0 pkg.LegalInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.LegalInfo, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.LegalInfo); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.LegalInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetOfferLegalInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfferLegalInfo'
type Client_GetOfferLegalInfo_Call struct {
	*mock.Call
}

// GetOfferLegalInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetOfferLegalInfo(ctx any, offerID any) *Client_GetOfferLegalInfo_Call {
	return &Client_GetOfferLegalInfo_Call{Call: _e.mock.On("GetOfferLegalInfo", ctx, offerID)}
}

func (_c *Client_GetOfferLegalInfo_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetOfferLegalInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetOfferLegalInfo_Call) Return(legalInfo pkg.LegalInfo, err error) *Client_GetOfferLegalInfo_Call {
	_c.Call.Return(legalInfo, err)
	return _c
}

func (_c *Client_GetOfferLegalInfo_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.LegalInfo, error)) *Client_GetOfferLegalInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfferWithContract provides a mock function for the type Client
func (_mock *Client) GetOfferWithContract(ctx context.Context, offerID uuid.UUID) (pkg.OfferWithContract, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetOfferWithContract")
	}

	var r0 pkg.OfferWithContract
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.OfferWithContract, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.OfferWithContract); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.OfferWithContract)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetOfferWithContract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfferWithContract'
type Client_GetOfferWithContract_Call struct {
	*mock.Call
}

// GetOfferWithContract is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetOfferWithContract(ctx any, offerID any) *Client_GetOfferWithContract_Call {
	return &Client_GetOfferWithContract_Call{Call: _e.mock.On("GetOfferWithContract", ctx, offerID)}
}

func (_c *Client_GetOfferWithContract_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetOfferWithContract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetOfferWithContract_Call) Return(offerWithContract pkg.OfferWithContract, err error) *Client_GetOfferWithContract_Call {
	_c.Call.Return(offerWithContract, err)
	return _c
}

func (_c *Client_GetOfferWithContract_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.OfferWithContract, error)) *Client_GetOfferWithContract_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type Client
func (_mock *Client) GetUserByID(ctx context.Context, userID string) (pkg.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 pkg.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (pkg.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) pkg.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(pkg.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Client_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Client_Expecter) GetUserByID(ctx any, userID any) *Client_GetUserByID_Call {
	return &Client_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *Client_GetUserByID_Call) Run(run func(ctx context.Context, userID string)) *Client_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetUserByID_Call) Return(user pkg.User, err error) *Client_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Client_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (pkg.User, error)) *Client_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByOfferID provides a mock function for the type Client
func (_mock *Client) GetUserByOfferID(ctx context.Context, offerID uuid.UUID) (pkg.User, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByOfferID")
	}

	var r0 pkg.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (pkg.User, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) pkg.User); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(pkg.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetUserByOfferID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByOfferID'
type Client_GetUserByOfferID_Call struct {
	*mock.Call
}

// GetUserByOfferID is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetUserByOfferID(ctx any, offerID any) *Client_GetUserByOfferID_Call {
	return &Client_GetUserByOfferID_Call{Call: _e.mock.On("GetUserByOfferID", ctx, offerID)}
}

func (_c *Client_GetUserByOfferID_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetUserByOfferID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetUserByOfferID_Call) Return(user pkg.User, err error) *Client_GetUserByOfferID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Client_GetUserByOfferID_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (pkg.User, error)) *Client_GetUserByOfferID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserWithOffersAndContracts provides a mock function for the type Client
func (_mock *Client) GetUserWithOffersAndContracts(ctx context.Context, userID string) (pkg.UserWithOffersAndContracts, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithOffersAndContracts")
	}

	var r0 pkg.UserWithOffersAndContracts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (pkg.UserWithOffersAndContracts, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) pkg.UserWithOffersAndContracts); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(pkg.UserWithOffersAndContracts)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetUserWithOffersAndContracts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserWithOffersAndContracts'
type Client_GetUserWithOffersAndContracts_Call struct {
	*mock.Call
}

// GetUserWithOffersAndContracts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *Client_Expecter) GetUserWithOffersAndContracts(ctx any, userID any) *Client_GetUserWithOffersAndContracts_Call {
	return &Client_GetUserWithOffersAndContracts_Call{Call: _e.mock.On("GetUserWithOffersAndContracts", ctx, userID)}
}

func (_c *Client_GetUserWithOffersAndContracts_Call) Run(run func(ctx context.Context, userID string)) *Client_GetUserWithOffersAndContracts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetUserWithOffersAndContracts_Call) Return(userWithOffersAndContracts pkg.UserWithOffersAndContracts, err error) *Client_GetUserWithOffersAndContracts_Call {
	_c.Call.Return(userWithOffersAndContracts, err)
	return _c
}

func (_c *Client_GetUserWithOffersAndContracts_Call) RunAndReturn(run func(ctx context.Context, userID string) (pkg.UserWithOffersAndContracts, error)) *Client_GetUserWithOffersAndContracts_Call {
	_c.Call.Return(run)
	return _c
}

// IterateHRInfo provides a mock function for the type Client
func (_mock *Client) IterateHRInfo(ctx context.Context, entity *jentity.Entity, active bool) iter.Seq2[pkg.HRInfo, error] {
	ret := _mock.Called(ctx, entity, active)

	if len(ret) == 0 {
		panic("no return value specified for IterateHRInfo")
	}

	var r0 iter.Seq2[pkg.HRInfo, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jentity.Entity, bool) iter.Seq2[pkg.HRInfo, error]); ok {
		r0 = returnFunc(ctx, entity, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[pkg.HRInfo, error])
		}
	}
	return r0
}

// Client_IterateHRInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IterateHRInfo'
type Client_IterateHRInfo_Call struct {
	*mock.Call
}

// IterateHRInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *jentity.Entity
//   - active bool
func (_e *Client_Expecter) IterateHRInfo(ctx any, entity any, active any) *Client_IterateHRInfo_Call {
	return &Client_IterateHRInfo_Call{Call: _e.mock.On("IterateHRInfo", ctx, entity, active)}
}

func (_c *Client_IterateHRInfo_Call) Run(run func(ctx context.Context, entity *jentity.Entity, active bool)) *Client_IterateHRInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *jentity.Entity
		if args[1] != nil {
			arg1 = args[1].(*jentity.Entity)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_IterateHRInfo_Call) Return(seq2 iter.Seq2[pkg.HRInfo, error]) *Client_IterateHRInfo_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *Client_IterateHRInfo_Call) RunAndReturn(run func(ctx context.Context, entity *jentity.Entity, active bool) iter.Seq2[pkg.HRInfo, error]) *Client_IterateHRInfo_Call {
	_c.Call.Return(run)
	return _c
}

// IterateUsersInfo provides a mock function for the type Client
func (_mock *Client) IterateUsersInfo(ctx context.Context, filters pkg.ListUsersInfoParams) iter.Seq2[pkg.UserInfo, error] {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for IterateUsersInfo")
	}

	var r0 iter.Seq2[pkg.UserInfo, error]
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkg.ListUsersInfoParams) iter.Seq2[pkg.UserInfo, error]); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq2[pkg.UserInfo, error])
		}
	}
	return r0
}

// Client_IterateUsersInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IterateUsersInfo'
type Client_IterateUsersInfo_Call struct {
	*mock.Call
}

// IterateUsersInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - filters pkg.ListUsersInfoParams
func (_e *Client_Expecter) IterateUsersInfo(ctx any, filters any) *Client_IterateUsersInfo_Call {
	return &Client_IterateUsersInfo_Call{Call: _e.mock.On("IterateUsersInfo", ctx, filters)}
}

func (_c *Client_IterateUsersInfo_Call) Run(run func(ctx context.Context, filters pkg.ListUsersInfoParams)) *Client_IterateUsersInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkg.ListUsersInfoParams
		if args[1] != nil {
			arg1 = args[1].(pkg.ListUsersInfoParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_IterateUsersInfo_Call) Return(seq2 iter.Seq2[pkg.UserInfo, error]) *Client_IterateUsersInfo_Call {
	_c.Call.Return(seq2)
	return _c
}

func (_c *Client_IterateUsersInfo_Call) RunAndReturn(run func(ctx context.Context, filters pkg.ListUsersInfoParams) iter.Seq2[pkg.UserInfo, error]) *Client_IterateUsersInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ListHRInfo provides a mock function for the type Client
func (_mock *Client) ListHRInfo(ctx context.Context, entity *jentity.Entity, active bool, pagination jdb.QueryPagination) ([]pkg.HRInfo, uint64, error) {
	ret := _mock.Called(ctx, entity, active, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListHRInfo")
	}

	var r0 []pkg.HRInfo
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jentity.Entity, bool, jdb.QueryPagination) ([]pkg.HRInfo, uint64, error)); ok {
		return returnFunc(ctx, entity, active, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *jentity.Entity, bool, jdb.QueryPagination) []pkg.HRInfo); ok {
		r0 = returnFunc(ctx, entity, active, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.HRInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *jentity.Entity, bool, jdb.QueryPagination) uint64); ok {
		r1 = returnFunc(ctx, entity, active, pagination)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *jentity.Entity, bool, jdb.QueryPagination) error); ok {
		r2 = returnFunc(ctx, entity, active, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_ListHRInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHRInfo'
type Client_ListHRInfo_Call struct {
	*mock.Call
}

// ListHRInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *jentity.Entity
//   - active bool
//   - pagination jdb.QueryPagination
func (_e *Client_Expecter) ListHRInfo(ctx any, entity any, active any, pagination any) *Client_ListHRInfo_Call {
	return &Client_ListHRInfo_Call{Call: _e.mock.On("ListHRInfo", ctx, entity, active, pagination)}
}

func (_c *Client_ListHRInfo_Call) Run(run func(ctx context.Context, entity *jentity.Entity, active bool, pagination jdb.QueryPagination)) *Client_ListHRInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *jentity.Entity
		if args[1] != nil {
			arg1 = args[1].(*jentity.Entity)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 jdb.QueryPagination
		if args[3] != nil {
			arg3 = args[3].(jdb.QueryPagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_ListHRInfo_Call) Return(hRInfos []pkg.HRInfo, v uint64, err error) *Client_ListHRInfo_Call {
	_c.Call.Return(hRInfos, v, err)
	return _c
}

func (_c *Client_ListHRInfo_Call) RunAndReturn(run func(ctx context.Context, entity *jentity.Entity, active bool, pagination jdb.QueryPagination) ([]pkg.HRInfo, uint64, error)) *Client_ListHRInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ListLifeOfferIDsByOwner provides a mock function for the type Client
func (_mock *Client) ListLifeOfferIDsByOwner(ctx context.Context, salesOwnerEmail string, csmOwnerEmail string) ([]uuid.UUID, error) {
	ret := _mock.Called(ctx, salesOwnerEmail, csmOwnerEmail)

	if len(ret) == 0 {
		panic("no return value specified for ListLifeOfferIDsByOwner")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, salesOwnerEmail, csmOwnerEmail)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []uuid.UUID); ok {
		r0 = returnFunc(ctx, salesOwnerEmail, csmOwnerEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, salesOwnerEmail, csmOwnerEmail)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ListLifeOfferIDsByOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLifeOfferIDsByOwner'
type Client_ListLifeOfferIDsByOwner_Call struct {
	*mock.Call
}

// ListLifeOfferIDsByOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - salesOwnerEmail string
//   - csmOwnerEmail string
func (_e *Client_Expecter) ListLifeOfferIDsByOwner(ctx any, salesOwnerEmail any, csmOwnerEmail any) *Client_ListLifeOfferIDsByOwner_Call {
	return &Client_ListLifeOfferIDsByOwner_Call{Call: _e.mock.On("ListLifeOfferIDsByOwner", ctx, salesOwnerEmail, csmOwnerEmail)}
}

func (_c *Client_ListLifeOfferIDsByOwner_Call) Run(run func(ctx context.Context, salesOwnerEmail string, csmOwnerEmail string)) *Client_ListLifeOfferIDsByOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_ListLifeOfferIDsByOwner_Call) Return(uUIDs []uuid.UUID, err error) *Client_ListLifeOfferIDsByOwner_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *Client_ListLifeOfferIDsByOwner_Call) RunAndReturn(run func(ctx context.Context, salesOwnerEmail string, csmOwnerEmail string) ([]uuid.UUID, error)) *Client_ListLifeOfferIDsByOwner_Call {
	_c.Call.Return(run)
	return _c
}

// ListOfferFiles provides a mock function for the type Client
func (_mock *Client) ListOfferFiles(ctx context.Context, offerID uuid.UUID, filters pkg.ListFileInfosFilters) ([]pkg.FileInfo, int64, error) {
	ret := _mock.Called(ctx, offerID, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListOfferFiles")
	}

	var r0 []pkg.FileInfo
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.ListFileInfosFilters) ([]pkg.FileInfo, int64, error)); ok {
		return returnFunc(ctx, offerID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.ListFileInfosFilters) []pkg.FileInfo); ok {
		r0 = returnFunc(ctx, offerID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, pkg.ListFileInfosFilters) int64); ok {
		r1 = returnFunc(ctx, offerID, filters)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, pkg.ListFileInfosFilters) error); ok {
		r2 = returnFunc(ctx, offerID, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_ListOfferFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOfferFiles'
type Client_ListOfferFiles_Call struct {
	*mock.Call
}

// ListOfferFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - filters pkg.ListFileInfosFilters
func (_e *Client_Expecter) ListOfferFiles(ctx any, offerID any, filters any) *Client_ListOfferFiles_Call {
	return &Client_ListOfferFiles_Call{Call: _e.mock.On("ListOfferFiles", ctx, offerID, filters)}
}

func (_c *Client_ListOfferFiles_Call) Run(run func(ctx context.Context, offerID uuid.UUID, filters pkg.ListFileInfosFilters)) *Client_ListOfferFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 pkg.ListFileInfosFilters
		if args[2] != nil {
			arg2 = args[2].(pkg.ListFileInfosFilters)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_ListOfferFiles_Call) Return(fileInfos []pkg.FileInfo, n int64, err error) *Client_ListOfferFiles_Call {
	_c.Call.Return(fileInfos, n, err)
	return _c
}

func (_c *Client_ListOfferFiles_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, filters pkg.ListFileInfosFilters) ([]pkg.FileInfo, int64, error)) *Client_ListOfferFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ListOffersByUserID provides a mock function for the type Client
func (_mock *Client) ListOffersByUserID(ctx context.Context, userID string, active *bool) ([]pkg.Offer, error) {
	ret := _mock.Called(ctx, userID, active)

	if len(ret) == 0 {
		panic("no return value specified for ListOffersByUserID")
	}

	var r0 []pkg.Offer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *bool) ([]pkg.Offer, error)); ok {
		return returnFunc(ctx, userID, active)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *bool) []pkg.Offer); ok {
		r0 = returnFunc(ctx, userID, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.Offer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *bool) error); ok {
		r1 = returnFunc(ctx, userID, active)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ListOffersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOffersByUserID'
type Client_ListOffersByUserID_Call struct {
	*mock.Call
}

// ListOffersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - active *bool
func (_e *Client_Expecter) ListOffersByUserID(ctx any, userID any, active any) *Client_ListOffersByUserID_Call {
	return &Client_ListOffersByUserID_Call{Call: _e.mock.On("ListOffersByUserID", ctx, userID, active)}
}

func (_c *Client_ListOffersByUserID_Call) Run(run func(ctx context.Context, userID string, active *bool)) *Client_ListOffersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *bool
		if args[2] != nil {
			arg2 = args[2].(*bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_ListOffersByUserID_Call) Return(offers []pkg.Offer, err error) *Client_ListOffersByUserID_Call {
	_c.Call.Return(offers, err)
	return _c
}

func (_c *Client_ListOffersByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string, active *bool) ([]pkg.Offer, error)) *Client_ListOffersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsersInfo provides a mock function for the type Client
func (_mock *Client) ListUsersInfo(ctx context.Context, filters pkg.ListUsersInfoParams) ([]pkg.UserInfo, uint64, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListUsersInfo")
	}

	var r0 []pkg.UserInfo
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkg.ListUsersInfoParams) ([]pkg.UserInfo, uint64, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkg.ListUsersInfoParams) []pkg.UserInfo); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.UserInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pkg.ListUsersInfoParams) uint64); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, pkg.ListUsersInfoParams) error); ok {
		r2 = returnFunc(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_ListUsersInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsersInfo'
type Client_ListUsersInfo_Call struct {
	*mock.Call
}

// ListUsersInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - filters pkg.ListUsersInfoParams
func (_e *Client_Expecter) ListUsersInfo(ctx any, filters any) *Client_ListUsersInfo_Call {
	return &Client_ListUsersInfo_Call{Call: _e.mock.On("ListUsersInfo", ctx, filters)}
}

func (_c *Client_ListUsersInfo_Call) Run(run func(ctx context.Context, filters pkg.ListUsersInfoParams)) *Client_ListUsersInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkg.ListUsersInfoParams
		if args[1] != nil {
			arg1 = args[1].(pkg.ListUsersInfoParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_ListUsersInfo_Call) Return(userInfos []pkg.UserInfo, v uint64, err error) *Client_ListUsersInfo_Call {
	_c.Call.Return(userInfos, v, err)
	return _c
}

func (_c *Client_ListUsersInfo_Call) RunAndReturn(run func(ctx context.Context, filters pkg.ListUsersInfoParams) ([]pkg.UserInfo, uint64, error)) *Client_ListUsersInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHRID provides a mock function for the type Client
func (_mock *Client) UpdateHRID(ctx context.Context, offerID uuid.UUID, hrID string) error {
	ret := _mock.Called(ctx, offerID, hrID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHRID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, offerID, hrID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UpdateHRID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHRID'
type Client_UpdateHRID_Call struct {
	*mock.Call
}

// UpdateHRID is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - hrID string
func (_e *Client_Expecter) UpdateHRID(ctx any, offerID any, hrID any) *Client_UpdateHRID_Call {
	return &Client_UpdateHRID_Call{Call: _e.mock.On("UpdateHRID", ctx, offerID, hrID)}
}

func (_c *Client_UpdateHRID_Call) Run(run func(ctx context.Context, offerID uuid.UUID, hrID string)) *Client_UpdateHRID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_UpdateHRID_Call) Return(err error) *Client_UpdateHRID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UpdateHRID_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, hrID string) error) *Client_UpdateHRID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIntercomID provides a mock function for the type Client
func (_mock *Client) UpdateIntercomID(ctx context.Context, userID string, intercomID string) error {
	ret := _mock.Called(ctx, userID, intercomID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIntercomID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, intercomID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UpdateIntercomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIntercomID'
type Client_UpdateIntercomID_Call struct {
	*mock.Call
}

// UpdateIntercomID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - intercomID string
func (_e *Client_Expecter) UpdateIntercomID(ctx any, userID any, intercomID any) *Client_UpdateIntercomID_Call {
	return &Client_UpdateIntercomID_Call{Call: _e.mock.On("UpdateIntercomID", ctx, userID, intercomID)}
}

func (_c *Client_UpdateIntercomID_Call) Run(run func(ctx context.Context, userID string, intercomID string)) *Client_UpdateIntercomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_UpdateIntercomID_Call) Return(err error) *Client_UpdateIntercomID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UpdateIntercomID_Call) RunAndReturn(run func(ctx context.Context, userID string, intercomID string) error) *Client_UpdateIntercomID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLifeOfferLegalInfo provides a mock function for the type Client
func (_mock *Client) UpdateLifeOfferLegalInfo(ctx context.Context, offerID uuid.UUID, newEntity jentity.Entity) error {
	ret := _mock.Called(ctx, offerID, newEntity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLifeOfferLegalInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jentity.Entity) error); ok {
		r0 = returnFunc(ctx, offerID, newEntity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UpdateLifeOfferLegalInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLifeOfferLegalInfo'
type Client_UpdateLifeOfferLegalInfo_Call struct {
	*mock.Call
}

// UpdateLifeOfferLegalInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - newEntity jentity.Entity
func (_e *Client_Expecter) UpdateLifeOfferLegalInfo(ctx any, offerID any, newEntity any) *Client_UpdateLifeOfferLegalInfo_Call {
	return &Client_UpdateLifeOfferLegalInfo_Call{Call: _e.mock.On("UpdateLifeOfferLegalInfo", ctx, offerID, newEntity)}
}

func (_c *Client_UpdateLifeOfferLegalInfo_Call) Run(run func(ctx context.Context, offerID uuid.UUID, newEntity jentity.Entity)) *Client_UpdateLifeOfferLegalInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 jentity.Entity
		if args[2] != nil {
			arg2 = args[2].(jentity.Entity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_UpdateLifeOfferLegalInfo_Call) Return(err error) *Client_UpdateLifeOfferLegalInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UpdateLifeOfferLegalInfo_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, newEntity jentity.Entity) error) *Client_UpdateLifeOfferLegalInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type Client
func (_mock *Client) UpdateUser(ctx context.Context, userID string, updateUser pkg.RequestUpdateUser) error {
	ret := _mock.Called(ctx, userID, updateUser)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, pkg.RequestUpdateUser) error); ok {
		r0 = returnFunc(ctx, userID, updateUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Client_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - updateUser pkg.RequestUpdateUser
func (_e *Client_Expecter) UpdateUser(ctx any, userID any, updateUser any) *Client_UpdateUser_Call {
	return &Client_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, userID, updateUser)}
}

func (_c *Client_UpdateUser_Call) Run(run func(ctx context.Context, userID string, updateUser pkg.RequestUpdateUser)) *Client_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 pkg.RequestUpdateUser
		if args[2] != nil {
			arg2 = args[2].(pkg.RequestUpdateUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_UpdateUser_Call) Return(err error) *Client_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, userID string, updateUser pkg.RequestUpdateUser) error) *Client_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserEmail provides a mock function for the type Client
func (_mock *Client) UpdateUserEmail(ctx context.Context, userID string, email string) error {
	ret := _mock.Called(ctx, userID, email)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UpdateUserEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserEmail'
type Client_UpdateUserEmail_Call struct {
	*mock.Call
}

// UpdateUserEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - email string
func (_e *Client_Expecter) UpdateUserEmail(ctx any, userID any, email any) *Client_UpdateUserEmail_Call {
	return &Client_UpdateUserEmail_Call{Call: _e.mock.On("UpdateUserEmail", ctx, userID, email)}
}

func (_c *Client_UpdateUserEmail_Call) Run(run func(ctx context.Context, userID string, email string)) *Client_UpdateUserEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_UpdateUserEmail_Call) Return(err error) *Client_UpdateUserEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UpdateUserEmail_Call) RunAndReturn(run func(ctx context.Context, userID string, email string) error) *Client_UpdateUserEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserProfile provides a mock function for the type Client
func (_mock *Client) UpdateUserProfile(ctx context.Context, userID string, profile pkg.UserPersonalInfo) error {
	ret := _mock.Called(ctx, userID, profile)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserProfile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, pkg.UserPersonalInfo) error); ok {
		r0 = returnFunc(ctx, userID, profile)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UpdateUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserProfile'
type Client_UpdateUserProfile_Call struct {
	*mock.Call
}

// UpdateUserProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - profile pkg.UserPersonalInfo
func (_e *Client_Expecter) UpdateUserProfile(ctx any, userID any, profile any) *Client_UpdateUserProfile_Call {
	return &Client_UpdateUserProfile_Call{Call: _e.mock.On("UpdateUserProfile", ctx, userID, profile)}
}

func (_c *Client_UpdateUserProfile_Call) Run(run func(ctx context.Context, userID string, profile pkg.UserPersonalInfo)) *Client_UpdateUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 pkg.UserPersonalInfo
		if args[2] != nil {
			arg2 = args[2].(pkg.UserPersonalInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_UpdateUserProfile_Call) Return(err error) *Client_UpdateUserProfile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UpdateUserProfile_Call) RunAndReturn(run func(ctx context.Context, userID string, profile pkg.UserPersonalInfo) error) *Client_UpdateUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UploadOfferFile provides a mock function for the type Client
func (_mock *Client) UploadOfferFile(ctx context.Context, offerID uuid.UUID, content []byte, filename string, fields map[string]string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, offerID, content, filename, fields)

	if len(ret) == 0 {
		panic("no return value specified for UploadOfferFile")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, string, map[string]string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, offerID, content, filename, fields)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, string, map[string]string) uuid.UUID); ok {
		r0 = returnFunc(ctx, offerID, content, filename, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []byte, string, map[string]string) error); ok {
		r1 = returnFunc(ctx, offerID, content, filename, fields)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_UploadOfferFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOfferFile'
type Client_UploadOfferFile_Call struct {
	*mock.Call
}

// UploadOfferFile is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - content []byte
//   - filename string
//   - fields map[string]string
func (_e *Client_Expecter) UploadOfferFile(ctx any, offerID any, content any, filename any, fields any) *Client_UploadOfferFile_Call {
	return &Client_UploadOfferFile_Call{Call: _e.mock.On("UploadOfferFile", ctx, offerID, content, filename, fields)}
}

func (_c *Client_UploadOfferFile_Call) Run(run func(ctx context.Context, offerID uuid.UUID, content []byte, filename string, fields map[string]string)) *Client_UploadOfferFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Client_UploadOfferFile_Call) Return(uUID uuid.UUID, err error) *Client_UploadOfferFile_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *Client_UploadOfferFile_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, content []byte, filename string, fields map[string]string) (uuid.UUID, error)) *Client_UploadOfferFile_Call {
	_c.Call.Return(run)
	return _c
}
