// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jdate"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewActivityReportStore creates a new instance of ActivityReportStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityReportStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityReportStore {
	mock := &ActivityReportStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ActivityReportStore is an autogenerated mock type for the ActivityReportStore type
type ActivityReportStore struct {
	mock.Mock
}

type ActivityReportStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityReportStore) EXPECT() *ActivityReportStore_Expecter {
	return &ActivityReportStore_Expecter{mock: &_m.Mock}
}

// CreateActivityReport provides a mock function for the type ActivityReportStore
func (_mock *ActivityReportStore) CreateActivityReport(ctx context.Context, report domain.Report) error {
	ret := _mock.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivityReport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Report) error); ok {
		r0 = returnFunc(ctx, report)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ActivityReportStore_CreateActivityReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivityReport'
type ActivityReportStore_CreateActivityReport_Call struct {
	*mock.Call
}

// CreateActivityReport is a helper method to define mock.On call
//   - ctx context.Context
//   - report domain.Report
func (_e *ActivityReportStore_Expecter) CreateActivityReport(ctx any, report any) *ActivityReportStore_CreateActivityReport_Call {
	return &ActivityReportStore_CreateActivityReport_Call{Call: _e.mock.On("CreateActivityReport", ctx, report)}
}

func (_c *ActivityReportStore_CreateActivityReport_Call) Run(run func(ctx context.Context, report domain.Report)) *ActivityReportStore_CreateActivityReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Report
		if args[1] != nil {
			arg1 = args[1].(domain.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActivityReportStore_CreateActivityReport_Call) Return(err error) *ActivityReportStore_CreateActivityReport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ActivityReportStore_CreateActivityReport_Call) RunAndReturn(run func(ctx context.Context, report domain.Report) error) *ActivityReportStore_CreateActivityReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityReportsByOfferID provides a mock function for the type ActivityReportStore
func (_mock *ActivityReportStore) GetActivityReportsByOfferID(ctx context.Context, offerID uuid.UUID) ([]domain.Report, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityReportsByOfferID")
	}

	var r0 []domain.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Report, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Report); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityReportStore_GetActivityReportsByOfferID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityReportsByOfferID'
type ActivityReportStore_GetActivityReportsByOfferID_Call struct {
	*mock.Call
}

// GetActivityReportsByOfferID is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *ActivityReportStore_Expecter) GetActivityReportsByOfferID(ctx any, offerID any) *ActivityReportStore_GetActivityReportsByOfferID_Call {
	return &ActivityReportStore_GetActivityReportsByOfferID_Call{Call: _e.mock.On("GetActivityReportsByOfferID", ctx, offerID)}
}

func (_c *ActivityReportStore_GetActivityReportsByOfferID_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *ActivityReportStore_GetActivityReportsByOfferID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActivityReportStore_GetActivityReportsByOfferID_Call) Return(reports []domain.Report, err error) *ActivityReportStore_GetActivityReportsByOfferID_Call {
	_c.Call.Return(reports, err)
	return _c
}

func (_c *ActivityReportStore_GetActivityReportsByOfferID_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) ([]domain.Report, error)) *ActivityReportStore_GetActivityReportsByOfferID_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivityReportsToGenerate provides a mock function for the type ActivityReportStore
func (_mock *ActivityReportStore) GetActivityReportsToGenerate(ctx context.Context) ([]domain.Report, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActivityReportsToGenerate")
	}

	var r0 []domain.Report
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Report, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Report); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Report)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityReportStore_GetActivityReportsToGenerate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivityReportsToGenerate'
type ActivityReportStore_GetActivityReportsToGenerate_Call struct {
	*mock.Call
}

// GetActivityReportsToGenerate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ActivityReportStore_Expecter) GetActivityReportsToGenerate(ctx any) *ActivityReportStore_GetActivityReportsToGenerate_Call {
	return &ActivityReportStore_GetActivityReportsToGenerate_Call{Call: _e.mock.On("GetActivityReportsToGenerate", ctx)}
}

func (_c *ActivityReportStore_GetActivityReportsToGenerate_Call) Run(run func(ctx context.Context)) *ActivityReportStore_GetActivityReportsToGenerate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ActivityReportStore_GetActivityReportsToGenerate_Call) Return(reports []domain.Report, err error) *ActivityReportStore_GetActivityReportsToGenerate_Call {
	_c.Call.Return(reports, err)
	return _c
}

func (_c *ActivityReportStore_GetActivityReportsToGenerate_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Report, error)) *ActivityReportStore_GetActivityReportsToGenerate_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissingActivityReportsByOfferID provides a mock function for the type ActivityReportStore
func (_mock *ActivityReportStore) GetMissingActivityReportsByOfferID(ctx context.Context, offerID uuid.UUID, from jdate.YearMonth, to jdate.YearMonth) ([]jdate.YearMonth, error) {
	ret := _mock.Called(ctx, offerID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetMissingActivityReportsByOfferID")
	}

	var r0 []jdate.YearMonth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth, jdate.YearMonth) ([]jdate.YearMonth, error)); ok {
		return returnFunc(ctx, offerID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth, jdate.YearMonth) []jdate.YearMonth); ok {
		r0 = returnFunc(ctx, offerID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jdate.YearMonth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, jdate.YearMonth, jdate.YearMonth) error); ok {
		r1 = returnFunc(ctx, offerID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityReportStore_GetMissingActivityReportsByOfferID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissingActivityReportsByOfferID'
type ActivityReportStore_GetMissingActivityReportsByOfferID_Call struct {
	*mock.Call
}

// GetMissingActivityReportsByOfferID is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - from jdate.YearMonth
//   - to jdate.YearMonth
func (_e *ActivityReportStore_Expecter) GetMissingActivityReportsByOfferID(ctx any, offerID any, from any, to any) *ActivityReportStore_GetMissingActivityReportsByOfferID_Call {
	return &ActivityReportStore_GetMissingActivityReportsByOfferID_Call{Call: _e.mock.On("GetMissingActivityReportsByOfferID", ctx, offerID, from, to)}
}

func (_c *ActivityReportStore_GetMissingActivityReportsByOfferID_Call) Run(run func(ctx context.Context, offerID uuid.UUID, from jdate.YearMonth, to jdate.YearMonth)) *ActivityReportStore_GetMissingActivityReportsByOfferID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 jdate.YearMonth
		if args[2] != nil {
			arg2 = args[2].(jdate.YearMonth)
		}
		var arg3 jdate.YearMonth
		if args[3] != nil {
			arg3 = args[3].(jdate.YearMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ActivityReportStore_GetMissingActivityReportsByOfferID_Call) Return(yearMonths []jdate.YearMonth, err error) *ActivityReportStore_GetMissingActivityReportsByOfferID_Call {
	_c.Call.Return(yearMonths, err)
	return _c
}

func (_c *ActivityReportStore_GetMissingActivityReportsByOfferID_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, from jdate.YearMonth, to jdate.YearMonth) ([]jdate.YearMonth, error)) *ActivityReportStore_GetMissingActivityReportsByOfferID_Call {
	_c.Call.Return(run)
	return _c
}

// SetReportAsGenerated provides a mock function for the type ActivityReportStore
func (_mock *ActivityReportStore) SetReportAsGenerated(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SetReportAsGenerated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ActivityReportStore_SetReportAsGenerated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReportAsGenerated'
type ActivityReportStore_SetReportAsGenerated_Call struct {
	*mock.Call
}

// SetReportAsGenerated is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ActivityReportStore_Expecter) SetReportAsGenerated(ctx any, id any) *ActivityReportStore_SetReportAsGenerated_Call {
	return &ActivityReportStore_SetReportAsGenerated_Call{Call: _e.mock.On("SetReportAsGenerated", ctx, id)}
}

func (_c *ActivityReportStore_SetReportAsGenerated_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ActivityReportStore_SetReportAsGenerated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActivityReportStore_SetReportAsGenerated_Call) Return(err error) *ActivityReportStore_SetReportAsGenerated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ActivityReportStore_SetReportAsGenerated_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *ActivityReportStore_SetReportAsGenerated_Call {
	_c.Call.Return(run)
	return _c
}
