// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jdate"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewActivityReportService creates a new instance of ActivityReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityReportService {
	mock := &ActivityReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ActivityReportService is an autogenerated mock type for the ActivityReportService type
type ActivityReportService struct {
	mock.Mock
}

type ActivityReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityReportService) EXPECT() *ActivityReportService_Expecter {
	return &ActivityReportService_Expecter{mock: &_m.Mock}
}

// CreateActivityReportsV3 provides a mock function for the type ActivityReportService
func (_mock *ActivityReportService) CreateActivityReportsV3(ctx context.Context, offerID uuid.UUID, reports []domain.Report) error {
	ret := _mock.Called(ctx, offerID, reports)

	if len(ret) == 0 {
		panic("no return value specified for CreateActivityReportsV3")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []domain.Report) error); ok {
		r0 = returnFunc(ctx, offerID, reports)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ActivityReportService_CreateActivityReportsV3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateActivityReportsV3'
type ActivityReportService_CreateActivityReportsV3_Call struct {
	*mock.Call
}

// CreateActivityReportsV3 is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - reports []domain.Report
func (_e *ActivityReportService_Expecter) CreateActivityReportsV3(ctx any, offerID any, reports any) *ActivityReportService_CreateActivityReportsV3_Call {
	return &ActivityReportService_CreateActivityReportsV3_Call{Call: _e.mock.On("CreateActivityReportsV3", ctx, offerID, reports)}
}

func (_c *ActivityReportService_CreateActivityReportsV3_Call) Run(run func(ctx context.Context, offerID uuid.UUID, reports []domain.Report)) *ActivityReportService_CreateActivityReportsV3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []domain.Report
		if args[2] != nil {
			arg2 = args[2].([]domain.Report)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ActivityReportService_CreateActivityReportsV3_Call) Return(err error) *ActivityReportService_CreateActivityReportsV3_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ActivityReportService_CreateActivityReportsV3_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, reports []domain.Report) error) *ActivityReportService_CreateActivityReportsV3_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateReportsPDFs provides a mock function for the type ActivityReportService
func (_mock *ActivityReportService) GenerateReportsPDFs(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateReportsPDFs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ActivityReportService_GenerateReportsPDFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateReportsPDFs'
type ActivityReportService_GenerateReportsPDFs_Call struct {
	*mock.Call
}

// GenerateReportsPDFs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ActivityReportService_Expecter) GenerateReportsPDFs(ctx any) *ActivityReportService_GenerateReportsPDFs_Call {
	return &ActivityReportService_GenerateReportsPDFs_Call{Call: _e.mock.On("GenerateReportsPDFs", ctx)}
}

func (_c *ActivityReportService_GenerateReportsPDFs_Call) Run(run func(ctx context.Context)) *ActivityReportService_GenerateReportsPDFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ActivityReportService_GenerateReportsPDFs_Call) Return(err error) *ActivityReportService_GenerateReportsPDFs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ActivityReportService_GenerateReportsPDFs_Call) RunAndReturn(run func(ctx context.Context) error) *ActivityReportService_GenerateReportsPDFs_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissingActivityReports provides a mock function for the type ActivityReportService
func (_mock *ActivityReportService) GetMissingActivityReports(ctx context.Context, offerID uuid.UUID) ([]jdate.YearMonth, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetMissingActivityReports")
	}

	var r0 []jdate.YearMonth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]jdate.YearMonth, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []jdate.YearMonth); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jdate.YearMonth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityReportService_GetMissingActivityReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissingActivityReports'
type ActivityReportService_GetMissingActivityReports_Call struct {
	*mock.Call
}

// GetMissingActivityReports is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *ActivityReportService_Expecter) GetMissingActivityReports(ctx any, offerID any) *ActivityReportService_GetMissingActivityReports_Call {
	return &ActivityReportService_GetMissingActivityReports_Call{Call: _e.mock.On("GetMissingActivityReports", ctx, offerID)}
}

func (_c *ActivityReportService_GetMissingActivityReports_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *ActivityReportService_GetMissingActivityReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActivityReportService_GetMissingActivityReports_Call) Return(yearMonths []jdate.YearMonth, err error) *ActivityReportService_GetMissingActivityReports_Call {
	_c.Call.Return(yearMonths, err)
	return _c
}

func (_c *ActivityReportService_GetMissingActivityReports_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) ([]jdate.YearMonth, error)) *ActivityReportService_GetMissingActivityReports_Call {
	_c.Call.Return(run)
	return _c
}
