// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/js3/v2"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewActivityReportGenerator creates a new instance of ActivityReportGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActivityReportGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActivityReportGenerator {
	mock := &ActivityReportGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ActivityReportGenerator is an autogenerated mock type for the ActivityReportGenerator type
type ActivityReportGenerator struct {
	mock.Mock
}

type ActivityReportGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *ActivityReportGenerator) EXPECT() *ActivityReportGenerator_Expecter {
	return &ActivityReportGenerator_Expecter{mock: &_m.Mock}
}

// GenerateActivityReport provides a mock function for the type ActivityReportGenerator
func (_mock *ActivityReportGenerator) GenerateActivityReport(ctx context.Context, report domain.Report) (js3.FileOutput, error) {
	ret := _mock.Called(ctx, report)

	if len(ret) == 0 {
		panic("no return value specified for GenerateActivityReport")
	}

	var r0 js3.FileOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Report) (js3.FileOutput, error)); ok {
		return returnFunc(ctx, report)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Report) js3.FileOutput); ok {
		r0 = returnFunc(ctx, report)
	} else {
		r0 = ret.Get(0).(js3.FileOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Report) error); ok {
		r1 = returnFunc(ctx, report)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ActivityReportGenerator_GenerateActivityReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateActivityReport'
type ActivityReportGenerator_GenerateActivityReport_Call struct {
	*mock.Call
}

// GenerateActivityReport is a helper method to define mock.On call
//   - ctx context.Context
//   - report domain.Report
func (_e *ActivityReportGenerator_Expecter) GenerateActivityReport(ctx any, report any) *ActivityReportGenerator_GenerateActivityReport_Call {
	return &ActivityReportGenerator_GenerateActivityReport_Call{Call: _e.mock.On("GenerateActivityReport", ctx, report)}
}

func (_c *ActivityReportGenerator_GenerateActivityReport_Call) Run(run func(ctx context.Context, report domain.Report)) *ActivityReportGenerator_GenerateActivityReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Report
		if args[1] != nil {
			arg1 = args[1].(domain.Report)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ActivityReportGenerator_GenerateActivityReport_Call) Return(fileOutput js3.FileOutput, err error) *ActivityReportGenerator_GenerateActivityReport_Call {
	_c.Call.Return(fileOutput, err)
	return _c
}

func (_c *ActivityReportGenerator_GenerateActivityReport_Call) RunAndReturn(run func(ctx context.Context, report domain.Report) (js3.FileOutput, error)) *ActivityReportGenerator_GenerateActivityReport_Call {
	_c.Call.Return(run)
	return _c
}
