// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jdate"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkScheduleStore creates a new instance of WorkScheduleStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkScheduleStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkScheduleStore {
	mock := &WorkScheduleStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkScheduleStore is an autogenerated mock type for the WorkScheduleStore type
type WorkScheduleStore struct {
	mock.Mock
}

type WorkScheduleStore_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkScheduleStore) EXPECT() *WorkScheduleStore_Expecter {
	return &WorkScheduleStore_Expecter{mock: &_m.Mock}
}

// AddWorkSchedule provides a mock function for the type WorkScheduleStore
func (_mock *WorkScheduleStore) AddWorkSchedule(ctx context.Context, offerID uuid.UUID, ws domain.WorkSchedule) error {
	ret := _mock.Called(ctx, offerID, ws)

	if len(ret) == 0 {
		panic("no return value specified for AddWorkSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.WorkSchedule) error); ok {
		r0 = returnFunc(ctx, offerID, ws)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkScheduleStore_AddWorkSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorkSchedule'
type WorkScheduleStore_AddWorkSchedule_Call struct {
	*mock.Call
}

// AddWorkSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - ws domain.WorkSchedule
func (_e *WorkScheduleStore_Expecter) AddWorkSchedule(ctx any, offerID any, ws any) *WorkScheduleStore_AddWorkSchedule_Call {
	return &WorkScheduleStore_AddWorkSchedule_Call{Call: _e.mock.On("AddWorkSchedule", ctx, offerID, ws)}
}

func (_c *WorkScheduleStore_AddWorkSchedule_Call) Run(run func(ctx context.Context, offerID uuid.UUID, ws domain.WorkSchedule)) *WorkScheduleStore_AddWorkSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.WorkSchedule
		if args[2] != nil {
			arg2 = args[2].(domain.WorkSchedule)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkScheduleStore_AddWorkSchedule_Call) Return(err error) *WorkScheduleStore_AddWorkSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkScheduleStore_AddWorkSchedule_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, ws domain.WorkSchedule) error) *WorkScheduleStore_AddWorkSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkSchedule provides a mock function for the type WorkScheduleStore
func (_mock *WorkScheduleStore) GetWorkSchedule(ctx context.Context, offerID uuid.UUID, month jdate.YearMonth) (domain.WorkSchedule, error) {
	ret := _mock.Called(ctx, offerID, month)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkSchedule")
	}

	var r0 domain.WorkSchedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth) (domain.WorkSchedule, error)); ok {
		return returnFunc(ctx, offerID, month)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth) domain.WorkSchedule); ok {
		r0 = returnFunc(ctx, offerID, month)
	} else {
		r0 = ret.Get(0).(domain.WorkSchedule)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, jdate.YearMonth) error); ok {
		r1 = returnFunc(ctx, offerID, month)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkScheduleStore_GetWorkSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkSchedule'
type WorkScheduleStore_GetWorkSchedule_Call struct {
	*mock.Call
}

// GetWorkSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - month jdate.YearMonth
func (_e *WorkScheduleStore_Expecter) GetWorkSchedule(ctx any, offerID any, month any) *WorkScheduleStore_GetWorkSchedule_Call {
	return &WorkScheduleStore_GetWorkSchedule_Call{Call: _e.mock.On("GetWorkSchedule", ctx, offerID, month)}
}

func (_c *WorkScheduleStore_GetWorkSchedule_Call) Run(run func(ctx context.Context, offerID uuid.UUID, month jdate.YearMonth)) *WorkScheduleStore_GetWorkSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 jdate.YearMonth
		if args[2] != nil {
			arg2 = args[2].(jdate.YearMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkScheduleStore_GetWorkSchedule_Call) Return(workSchedule domain.WorkSchedule, err error) *WorkScheduleStore_GetWorkSchedule_Call {
	_c.Call.Return(workSchedule, err)
	return _c
}

func (_c *WorkScheduleStore_GetWorkSchedule_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, month jdate.YearMonth) (domain.WorkSchedule, error)) *WorkScheduleStore_GetWorkSchedule_Call {
	_c.Call.Return(run)
	return _c
}
