// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/Freelance-launchpad/backend-interview/common/jdate"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/internal/domain"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/pkg"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewWorkScheduleService creates a new instance of WorkScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkScheduleService {
	mock := &WorkScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WorkScheduleService is an autogenerated mock type for the WorkScheduleService type
type WorkScheduleService struct {
	mock.Mock
}

type WorkScheduleService_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkScheduleService) EXPECT() *WorkScheduleService_Expecter {
	return &WorkScheduleService_Expecter{mock: &_m.Mock}
}

// GetMonthConfiguration provides a mock function for the type WorkScheduleService
func (_mock *WorkScheduleService) GetMonthConfiguration(ctx context.Context, offerID uuid.UUID, period jdate.YearMonth) (domain.MonthConfiguration, error) {
	ret := _mock.Called(ctx, offerID, period)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthConfiguration")
	}

	var r0 domain.MonthConfiguration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth) (domain.MonthConfiguration, error)); ok {
		return returnFunc(ctx, offerID, period)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth) domain.MonthConfiguration); ok {
		r0 = returnFunc(ctx, offerID, period)
	} else {
		r0 = ret.Get(0).(domain.MonthConfiguration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, jdate.YearMonth) error); ok {
		r1 = returnFunc(ctx, offerID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkScheduleService_GetMonthConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMonthConfiguration'
type WorkScheduleService_GetMonthConfiguration_Call struct {
	*mock.Call
}

// GetMonthConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - period jdate.YearMonth
func (_e *WorkScheduleService_Expecter) GetMonthConfiguration(ctx any, offerID any, period any) *WorkScheduleService_GetMonthConfiguration_Call {
	return &WorkScheduleService_GetMonthConfiguration_Call{Call: _e.mock.On("GetMonthConfiguration", ctx, offerID, period)}
}

func (_c *WorkScheduleService_GetMonthConfiguration_Call) Run(run func(ctx context.Context, offerID uuid.UUID, period jdate.YearMonth)) *WorkScheduleService_GetMonthConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 jdate.YearMonth
		if args[2] != nil {
			arg2 = args[2].(jdate.YearMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkScheduleService_GetMonthConfiguration_Call) Return(monthConfiguration domain.MonthConfiguration, err error) *WorkScheduleService_GetMonthConfiguration_Call {
	_c.Call.Return(monthConfiguration, err)
	return _c
}

func (_c *WorkScheduleService_GetMonthConfiguration_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, period jdate.YearMonth) (domain.MonthConfiguration, error)) *WorkScheduleService_GetMonthConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkScheduleStatus provides a mock function for the type WorkScheduleService
func (_mock *WorkScheduleService) GetWorkScheduleStatus(ctx context.Context, offerID uuid.UUID, at time.Time) (domain.WorkScheduleStatus, error) {
	ret := _mock.Called(ctx, offerID, at)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkScheduleStatus")
	}

	var r0 domain.WorkScheduleStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) (domain.WorkScheduleStatus, error)); ok {
		return returnFunc(ctx, offerID, at)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) domain.WorkScheduleStatus); ok {
		r0 = returnFunc(ctx, offerID, at)
	} else {
		r0 = ret.Get(0).(domain.WorkScheduleStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r1 = returnFunc(ctx, offerID, at)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WorkScheduleService_GetWorkScheduleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkScheduleStatus'
type WorkScheduleService_GetWorkScheduleStatus_Call struct {
	*mock.Call
}

// GetWorkScheduleStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - at time.Time
func (_e *WorkScheduleService_Expecter) GetWorkScheduleStatus(ctx any, offerID any, at any) *WorkScheduleService_GetWorkScheduleStatus_Call {
	return &WorkScheduleService_GetWorkScheduleStatus_Call{Call: _e.mock.On("GetWorkScheduleStatus", ctx, offerID, at)}
}

func (_c *WorkScheduleService_GetWorkScheduleStatus_Call) Run(run func(ctx context.Context, offerID uuid.UUID, at time.Time)) *WorkScheduleService_GetWorkScheduleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkScheduleService_GetWorkScheduleStatus_Call) Return(workScheduleStatus domain.WorkScheduleStatus, err error) *WorkScheduleService_GetWorkScheduleStatus_Call {
	_c.Call.Return(workScheduleStatus, err)
	return _c
}

func (_c *WorkScheduleService_GetWorkScheduleStatus_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, at time.Time) (domain.WorkScheduleStatus, error)) *WorkScheduleService_GetWorkScheduleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetWorkSchedule provides a mock function for the type WorkScheduleService
func (_mock *WorkScheduleService) SetWorkSchedule(ctx context.Context, offerID uuid.UUID, weekType pkg.WeekType) error {
	ret := _mock.Called(ctx, offerID, weekType)

	if len(ret) == 0 {
		panic("no return value specified for SetWorkSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.WeekType) error); ok {
		r0 = returnFunc(ctx, offerID, weekType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// WorkScheduleService_SetWorkSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWorkSchedule'
type WorkScheduleService_SetWorkSchedule_Call struct {
	*mock.Call
}

// SetWorkSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - weekType pkg.WeekType
func (_e *WorkScheduleService_Expecter) SetWorkSchedule(ctx any, offerID any, weekType any) *WorkScheduleService_SetWorkSchedule_Call {
	return &WorkScheduleService_SetWorkSchedule_Call{Call: _e.mock.On("SetWorkSchedule", ctx, offerID, weekType)}
}

func (_c *WorkScheduleService_SetWorkSchedule_Call) Run(run func(ctx context.Context, offerID uuid.UUID, weekType pkg.WeekType)) *WorkScheduleService_SetWorkSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 pkg.WeekType
		if args[2] != nil {
			arg2 = args[2].(pkg.WeekType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *WorkScheduleService_SetWorkSchedule_Call) Return(err error) *WorkScheduleService_SetWorkSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *WorkScheduleService_SetWorkSchedule_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, weekType pkg.WeekType) error) *WorkScheduleService_SetWorkSchedule_Call {
	_c.Call.Return(run)
	return _c
}
