// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jdate"
	"github.com/Freelance-launchpad/backend-interview/services/activity-reports/pkg"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetRestDays provides a mock function for the type Client
func (_mock *Client) GetRestDays(ctx context.Context, offerID uuid.UUID, period jdate.YearMonth) (pkg.RestDaysResponse, error) {
	ret := _mock.Called(ctx, offerID, period)

	if len(ret) == 0 {
		panic("no return value specified for GetRestDays")
	}

	var r0 pkg.RestDaysResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth) (pkg.RestDaysResponse, error)); ok {
		return returnFunc(ctx, offerID, period)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.YearMonth) pkg.RestDaysResponse); ok {
		r0 = returnFunc(ctx, offerID, period)
	} else {
		r0 = ret.Get(0).(pkg.RestDaysResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, jdate.YearMonth) error); ok {
		r1 = returnFunc(ctx, offerID, period)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetRestDays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestDays'
type Client_GetRestDays_Call struct {
	*mock.Call
}

// GetRestDays is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - period jdate.YearMonth
func (_e *Client_Expecter) GetRestDays(ctx any, offerID any, period any) *Client_GetRestDays_Call {
	return &Client_GetRestDays_Call{Call: _e.mock.On("GetRestDays", ctx, offerID, period)}
}

func (_c *Client_GetRestDays_Call) Run(run func(ctx context.Context, offerID uuid.UUID, period jdate.YearMonth)) *Client_GetRestDays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 jdate.YearMonth
		if args[2] != nil {
			arg2 = args[2].(jdate.YearMonth)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetRestDays_Call) Return(restDaysResponse pkg.RestDaysResponse, err error) *Client_GetRestDays_Call {
	_c.Call.Return(restDaysResponse, err)
	return _c
}

func (_c *Client_GetRestDays_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, period jdate.YearMonth) (pkg.RestDaysResponse, error)) *Client_GetRestDays_Call {
	_c.Call.Return(run)
	return _c
}
