configuration:
  authorization:
    jwk_url: "https://staging-jump.eu.auth0.com/.well-known/jwks.json"
    iss: "https://staging-jump.eu.auth0.com/"
    custom_field_prefix: "https://staging.jumptest.link"

  database:
    host: "shared-database.app.svc.cluster.local"
    port: 5432
    user: "activity-reports"
    name: "activity-reports"

  auth_url: "http://auth/"
  users_url: "http://users/"
  expenses_url: "http://expenses-api/"
  payroll_url: "http://payroll/"
