// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewS3PresignerAPI creates a new instance of S3PresignerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3PresignerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3PresignerAPI {
	mock := &S3PresignerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3PresignerAPI is an autogenerated mock type for the s3PresignerAPI type
type S3PresignerAPI struct {
	mock.Mock
}

type S3PresignerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *S3PresignerAPI) EXPECT() *S3PresignerAPI_Expecter {
	return &S3PresignerAPI_Expecter{mock: &_m.Mock}
}

// PresignGetObject provides a mock function for the type S3PresignerAPI
func (_mock *S3PresignerAPI) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	// func(*s3.PresignOptions)
	_va := make([]any, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PresignGetObject")
	}

	var r0 *v4.PresignedHTTPRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) *v4.PresignedHTTPRequest); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v4.PresignedHTTPRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3PresignerAPI_PresignGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetObject'
type S3PresignerAPI_PresignGetObject_Call struct {
	*mock.Call
}

// PresignGetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - params *s3.GetObjectInput
//   - optFns ...func(*s3.PresignOptions)
func (_e *S3PresignerAPI_Expecter) PresignGetObject(ctx any, params any, optFns ...any) *S3PresignerAPI_PresignGetObject_Call {
	return &S3PresignerAPI_PresignGetObject_Call{Call: _e.mock.On("PresignGetObject",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *S3PresignerAPI_PresignGetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions))) *S3PresignerAPI_PresignGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.PresignOptions)
		variadicArgs := make([]func(*s3.PresignOptions), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*s3.PresignOptions))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3PresignerAPI_PresignGetObject_Call) Return(presignedHTTPRequest *v4.PresignedHTTPRequest, err error) *S3PresignerAPI_PresignGetObject_Call {
	_c.Call.Return(presignedHTTPRequest, err)
	return _c
}

func (_c *S3PresignerAPI_PresignGetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *S3PresignerAPI_PresignGetObject_Call {
	_c.Call.Return(run)
	return _c
}
