// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/feature/s3/transfermanager"
	mock "github.com/stretchr/testify/mock"
)

// NewS3UploaderAPI creates a new instance of S3UploaderAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3UploaderAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3UploaderAPI {
	mock := &S3UploaderAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3UploaderAPI is an autogenerated mock type for the s3UploaderAPI type
type S3UploaderAPI struct {
	mock.Mock
}

type S3UploaderAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *S3UploaderAPI) EXPECT() *S3UploaderAPI_Expecter {
	return &S3UploaderAPI_Expecter{mock: &_m.Mock}
}

// UploadObject provides a mock function for the type S3UploaderAPI
func (_mock *S3UploaderAPI) UploadObject(ctx context.Context, input *transfermanager.UploadObjectInput, opts ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error) {
	// func(*transfermanager.Options)
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UploadObject")
	}

	var r0 *transfermanager.UploadObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) *transfermanager.UploadObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transfermanager.UploadObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *transfermanager.UploadObjectInput, ...func(*transfermanager.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3UploaderAPI_UploadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadObject'
type S3UploaderAPI_UploadObject_Call struct {
	*mock.Call
}

// UploadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *transfermanager.UploadObjectInput
//   - opts ...func(*transfermanager.Options)
func (_e *S3UploaderAPI_Expecter) UploadObject(ctx any, input any, opts ...any) *S3UploaderAPI_UploadObject_Call {
	return &S3UploaderAPI_UploadObject_Call{Call: _e.mock.On("UploadObject",
		append([]any{ctx, input}, opts...)...)}
}

func (_c *S3UploaderAPI_UploadObject_Call) Run(run func(ctx context.Context, input *transfermanager.UploadObjectInput, opts ...func(*transfermanager.Options))) *S3UploaderAPI_UploadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *transfermanager.UploadObjectInput
		if args[1] != nil {
			arg1 = args[1].(*transfermanager.UploadObjectInput)
		}
		var arg2 []func(*transfermanager.Options)
		variadicArgs := make([]func(*transfermanager.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*transfermanager.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3UploaderAPI_UploadObject_Call) Return(uploadObjectOutput *transfermanager.UploadObjectOutput, err error) *S3UploaderAPI_UploadObject_Call {
	_c.Call.Return(uploadObjectOutput, err)
	return _c
}

func (_c *S3UploaderAPI_UploadObject_Call) RunAndReturn(run func(ctx context.Context, input *transfermanager.UploadObjectInput, opts ...func(*transfermanager.Options)) (*transfermanager.UploadObjectOutput, error)) *S3UploaderAPI_UploadObject_Call {
	_c.Call.Return(run)
	return _c
}
