// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/Freelance-launchpad/backend-interview/common/js3/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewFileProvider creates a new instance of FileProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileProvider {
	mock := &FileProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileProvider is an autogenerated mock type for the FileProvider type
type FileProvider struct {
	mock.Mock
}

type FileProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *FileProvider) EXPECT() *FileProvider_Expecter {
	return &FileProvider_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type FileProvider
func (_mock *FileProvider) Delete(ctx context.Context, identifier string) error {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FileProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *FileProvider_Expecter) Delete(ctx any, identifier any) *FileProvider_Delete_Call {
	return &FileProvider_Delete_Call{Call: _e.mock.On("Delete", ctx, identifier)}
}

func (_c *FileProvider_Delete_Call) Run(run func(ctx context.Context, identifier string)) *FileProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileProvider_Delete_Call) Return(err error) *FileProvider_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileProvider_Delete_Call) RunAndReturn(run func(ctx context.Context, identifier string) error) *FileProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function for the type FileProvider
func (_mock *FileProvider) Download(ctx context.Context, identifier string) (js3.FileOutput, error) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 js3.FileOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (js3.FileOutput, error)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) js3.FileOutput); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		r0 = ret.Get(0).(js3.FileOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileProvider_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type FileProvider_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *FileProvider_Expecter) Download(ctx any, identifier any) *FileProvider_Download_Call {
	return &FileProvider_Download_Call{Call: _e.mock.On("Download", ctx, identifier)}
}

func (_c *FileProvider_Download_Call) Run(run func(ctx context.Context, identifier string)) *FileProvider_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileProvider_Download_Call) Return(fileOutput js3.FileOutput, err error) *FileProvider_Download_Call {
	_c.Call.Return(fileOutput, err)
	return _c
}

func (_c *FileProvider_Download_Call) RunAndReturn(run func(ctx context.Context, identifier string) (js3.FileOutput, error)) *FileProvider_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GetURL provides a mock function for the type FileProvider
func (_mock *FileProvider) GetURL(ctx context.Context, identifier string) (string, error) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileProvider_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type FileProvider_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *FileProvider_Expecter) GetURL(ctx any, identifier any) *FileProvider_GetURL_Call {
	return &FileProvider_GetURL_Call{Call: _e.mock.On("GetURL", ctx, identifier)}
}

func (_c *FileProvider_GetURL_Call) Run(run func(ctx context.Context, identifier string)) *FileProvider_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileProvider_GetURL_Call) Return(s string, err error) *FileProvider_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *FileProvider_GetURL_Call) RunAndReturn(run func(ctx context.Context, identifier string) (string, error)) *FileProvider_GetURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetURLWithMetadata provides a mock function for the type FileProvider
func (_mock *FileProvider) GetURLWithMetadata(ctx context.Context, identifier string) (string, map[string]string, error) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetURLWithMetadata")
	}

	var r0 string
	var r1 map[string]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, map[string]string, error)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) map[string]string); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, identifier)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FileProvider_GetURLWithMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURLWithMetadata'
type FileProvider_GetURLWithMetadata_Call struct {
	*mock.Call
}

// GetURLWithMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *FileProvider_Expecter) GetURLWithMetadata(ctx any, identifier any) *FileProvider_GetURLWithMetadata_Call {
	return &FileProvider_GetURLWithMetadata_Call{Call: _e.mock.On("GetURLWithMetadata", ctx, identifier)}
}

func (_c *FileProvider_GetURLWithMetadata_Call) Run(run func(ctx context.Context, identifier string)) *FileProvider_GetURLWithMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileProvider_GetURLWithMetadata_Call) Return(s string, stringToString map[string]string, err error) *FileProvider_GetURLWithMetadata_Call {
	_c.Call.Return(s, stringToString, err)
	return _c
}

func (_c *FileProvider_GetURLWithMetadata_Call) RunAndReturn(run func(ctx context.Context, identifier string) (string, map[string]string, error)) *FileProvider_GetURLWithMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type FileProvider
func (_mock *FileProvider) Store(ctx context.Context, identifier string, readSeeker io.ReadSeeker) error {
	ret := _mock.Called(ctx, identifier, readSeeker)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.ReadSeeker) error); ok {
		r0 = returnFunc(ctx, identifier, readSeeker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileProvider_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type FileProvider_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - readSeeker io.ReadSeeker
func (_e *FileProvider_Expecter) Store(ctx any, identifier any, readSeeker any) *FileProvider_Store_Call {
	return &FileProvider_Store_Call{Call: _e.mock.On("Store", ctx, identifier, readSeeker)}
}

func (_c *FileProvider_Store_Call) Run(run func(ctx context.Context, identifier string, readSeeker io.ReadSeeker)) *FileProvider_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.ReadSeeker
		if args[2] != nil {
			arg2 = args[2].(io.ReadSeeker)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FileProvider_Store_Call) Return(err error) *FileProvider_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileProvider_Store_Call) RunAndReturn(run func(ctx context.Context, identifier string, readSeeker io.ReadSeeker) error) *FileProvider_Store_Call {
	_c.Call.Return(run)
	return _c
}

// StoreWithMetadata provides a mock function for the type FileProvider
func (_mock *FileProvider) StoreWithMetadata(ctx context.Context, identifier string, metadata map[string]string, readSeeker io.ReadSeeker) error {
	ret := _mock.Called(ctx, identifier, metadata, readSeeker)

	if len(ret) == 0 {
		panic("no return value specified for StoreWithMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]string, io.ReadSeeker) error); ok {
		r0 = returnFunc(ctx, identifier, metadata, readSeeker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileProvider_StoreWithMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreWithMetadata'
type FileProvider_StoreWithMetadata_Call struct {
	*mock.Call
}

// StoreWithMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - metadata map[string]string
//   - readSeeker io.ReadSeeker
func (_e *FileProvider_Expecter) StoreWithMetadata(ctx any, identifier any, metadata any, readSeeker any) *FileProvider_StoreWithMetadata_Call {
	return &FileProvider_StoreWithMetadata_Call{Call: _e.mock.On("StoreWithMetadata", ctx, identifier, metadata, readSeeker)}
}

func (_c *FileProvider_StoreWithMetadata_Call) Run(run func(ctx context.Context, identifier string, metadata map[string]string, readSeeker io.ReadSeeker)) *FileProvider_StoreWithMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 io.ReadSeeker
		if args[3] != nil {
			arg3 = args[3].(io.ReadSeeker)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FileProvider_StoreWithMetadata_Call) Return(err error) *FileProvider_StoreWithMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileProvider_StoreWithMetadata_Call) RunAndReturn(run func(ctx context.Context, identifier string, metadata map[string]string, readSeeker io.ReadSeeker) error) *FileProvider_StoreWithMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// StoreWithMetadataAndContentType provides a mock function for the type FileProvider
func (_mock *FileProvider) StoreWithMetadataAndContentType(ctx context.Context, identifier string, contentType string, metadata map[string]string, readSeeker io.ReadSeeker) error {
	ret := _mock.Called(ctx, identifier, contentType, metadata, readSeeker)

	if len(ret) == 0 {
		panic("no return value specified for StoreWithMetadataAndContentType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, io.ReadSeeker) error); ok {
		r0 = returnFunc(ctx, identifier, contentType, metadata, readSeeker)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileProvider_StoreWithMetadataAndContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreWithMetadataAndContentType'
type FileProvider_StoreWithMetadataAndContentType_Call struct {
	*mock.Call
}

// StoreWithMetadataAndContentType is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
//   - contentType string
//   - metadata map[string]string
//   - readSeeker io.ReadSeeker
func (_e *FileProvider_Expecter) StoreWithMetadataAndContentType(ctx any, identifier any, contentType any, metadata any, readSeeker any) *FileProvider_StoreWithMetadataAndContentType_Call {
	return &FileProvider_StoreWithMetadataAndContentType_Call{Call: _e.mock.On("StoreWithMetadataAndContentType", ctx, identifier, contentType, metadata, readSeeker)}
}

func (_c *FileProvider_StoreWithMetadataAndContentType_Call) Run(run func(ctx context.Context, identifier string, contentType string, metadata map[string]string, readSeeker io.ReadSeeker)) *FileProvider_StoreWithMetadataAndContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		var arg4 io.ReadSeeker
		if args[4] != nil {
			arg4 = args[4].(io.ReadSeeker)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *FileProvider_StoreWithMetadataAndContentType_Call) Return(err error) *FileProvider_StoreWithMetadataAndContentType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileProvider_StoreWithMetadataAndContentType_Call) RunAndReturn(run func(ctx context.Context, identifier string, contentType string, metadata map[string]string, readSeeker io.ReadSeeker) error) *FileProvider_StoreWithMetadataAndContentType_Call {
	_c.Call.Return(run)
	return _c
}
