// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// HTMLToFacturXPDF provides a mock function for the type Client
func (_mock *Client) HTMLToFacturXPDF(ctx context.Context, content io.Reader, footer io.Reader, facturx io.Reader) (int64, io.ReadSeeker, error) {
	ret := _mock.Called(ctx, content, footer, facturx)

	if len(ret) == 0 {
		panic("no return value specified for HTMLToFacturXPDF")
	}

	var r0 int64
	var r1 io.ReadSeeker
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, io.Reader, io.Reader) (int64, io.ReadSeeker, error)); ok {
		return returnFunc(ctx, content, footer, facturx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, io.Reader, io.Reader) int64); ok {
		r0 = returnFunc(ctx, content, footer, facturx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, io.Reader, io.Reader) io.ReadSeeker); ok {
		r1 = returnFunc(ctx, content, footer, facturx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadSeeker)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.Reader, io.Reader, io.Reader) error); ok {
		r2 = returnFunc(ctx, content, footer, facturx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_HTMLToFacturXPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTMLToFacturXPDF'
type Client_HTMLToFacturXPDF_Call struct {
	*mock.Call
}

// HTMLToFacturXPDF is a helper method to define mock.On call
//   - ctx context.Context
//   - content io.Reader
//   - footer io.Reader
//   - facturx io.Reader
func (_e *Client_Expecter) HTMLToFacturXPDF(ctx any, content any, footer any, facturx any) *Client_HTMLToFacturXPDF_Call {
	return &Client_HTMLToFacturXPDF_Call{Call: _e.mock.On("HTMLToFacturXPDF", ctx, content, footer, facturx)}
}

func (_c *Client_HTMLToFacturXPDF_Call) Run(run func(ctx context.Context, content io.Reader, footer io.Reader, facturx io.Reader)) *Client_HTMLToFacturXPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_HTMLToFacturXPDF_Call) Return(n int64, readSeeker io.ReadSeeker, err error) *Client_HTMLToFacturXPDF_Call {
	_c.Call.Return(n, readSeeker, err)
	return _c
}

func (_c *Client_HTMLToFacturXPDF_Call) RunAndReturn(run func(ctx context.Context, content io.Reader, footer io.Reader, facturx io.Reader) (int64, io.ReadSeeker, error)) *Client_HTMLToFacturXPDF_Call {
	_c.Call.Return(run)
	return _c
}

// HTMLToPDF provides a mock function for the type Client
func (_mock *Client) HTMLToPDF(ctx context.Context, content io.Reader, footer io.Reader) (int64, io.ReadSeeker, error) {
	ret := _mock.Called(ctx, content, footer)

	if len(ret) == 0 {
		panic("no return value specified for HTMLToPDF")
	}

	var r0 int64
	var r1 io.ReadSeeker
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, io.Reader) (int64, io.ReadSeeker, error)); ok {
		return returnFunc(ctx, content, footer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, io.Reader) int64); ok {
		r0 = returnFunc(ctx, content, footer)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, io.Reader) io.ReadSeeker); ok {
		r1 = returnFunc(ctx, content, footer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadSeeker)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.Reader, io.Reader) error); ok {
		r2 = returnFunc(ctx, content, footer)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_HTMLToPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTMLToPDF'
type Client_HTMLToPDF_Call struct {
	*mock.Call
}

// HTMLToPDF is a helper method to define mock.On call
//   - ctx context.Context
//   - content io.Reader
//   - footer io.Reader
func (_e *Client_Expecter) HTMLToPDF(ctx any, content any, footer any) *Client_HTMLToPDF_Call {
	return &Client_HTMLToPDF_Call{Call: _e.mock.On("HTMLToPDF", ctx, content, footer)}
}

func (_c *Client_HTMLToPDF_Call) Run(run func(ctx context.Context, content io.Reader, footer io.Reader)) *Client_HTMLToPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_HTMLToPDF_Call) Return(n int64, readSeeker io.ReadSeeker, err error) *Client_HTMLToPDF_Call {
	_c.Call.Return(n, readSeeker, err)
	return _c
}

func (_c *Client_HTMLToPDF_Call) RunAndReturn(run func(ctx context.Context, content io.Reader, footer io.Reader) (int64, io.ReadSeeker, error)) *Client_HTMLToPDF_Call {
	_c.Call.Return(run)
	return _c
}

// MergePDFs provides a mock function for the type Client
func (_mock *Client) MergePDFs(ctx context.Context, files []io.Reader) (io.ReadSeeker, int64, error) {
	ret := _mock.Called(ctx, files)

	if len(ret) == 0 {
		panic("no return value specified for MergePDFs")
	}

	var r0 io.ReadSeeker
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []io.Reader) (io.ReadSeeker, int64, error)); ok {
		return returnFunc(ctx, files)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []io.Reader) io.ReadSeeker); ok {
		r0 = returnFunc(ctx, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeeker)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []io.Reader) int64); ok {
		r1 = returnFunc(ctx, files)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []io.Reader) error); ok {
		r2 = returnFunc(ctx, files)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_MergePDFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergePDFs'
type Client_MergePDFs_Call struct {
	*mock.Call
}

// MergePDFs is a helper method to define mock.On call
//   - ctx context.Context
//   - files []io.Reader
func (_e *Client_Expecter) MergePDFs(ctx any, files any) *Client_MergePDFs_Call {
	return &Client_MergePDFs_Call{Call: _e.mock.On("MergePDFs", ctx, files)}
}

func (_c *Client_MergePDFs_Call) Run(run func(ctx context.Context, files []io.Reader)) *Client_MergePDFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []io.Reader
		if args[1] != nil {
			arg1 = args[1].([]io.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_MergePDFs_Call) Return(file io.ReadSeeker, length int64, err error) *Client_MergePDFs_Call {
	_c.Call.Return(file, length, err)
	return _c
}

func (_c *Client_MergePDFs_Call) RunAndReturn(run func(ctx context.Context, files []io.Reader) (io.ReadSeeker, int64, error)) *Client_MergePDFs_Call {
	_c.Call.Return(run)
	return _c
}

// StampPDF provides a mock function for the type Client
func (_mock *Client) StampPDF(ctx context.Context, file io.Reader, stamp io.Reader) (int64, io.ReadSeeker, error) {
	ret := _mock.Called(ctx, file, stamp)

	if len(ret) == 0 {
		panic("no return value specified for StampPDF")
	}

	var r0 int64
	var r1 io.ReadSeeker
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, io.Reader) (int64, io.ReadSeeker, error)); ok {
		return returnFunc(ctx, file, stamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.Reader, io.Reader) int64); ok {
		r0 = returnFunc(ctx, file, stamp)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.Reader, io.Reader) io.ReadSeeker); ok {
		r1 = returnFunc(ctx, file, stamp)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.ReadSeeker)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.Reader, io.Reader) error); ok {
		r2 = returnFunc(ctx, file, stamp)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_StampPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StampPDF'
type Client_StampPDF_Call struct {
	*mock.Call
}

// StampPDF is a helper method to define mock.On call
//   - ctx context.Context
//   - file io.Reader
//   - stamp io.Reader
func (_e *Client_Expecter) StampPDF(ctx any, file any, stamp any) *Client_StampPDF_Call {
	return &Client_StampPDF_Call{Call: _e.mock.On("StampPDF", ctx, file, stamp)}
}

func (_c *Client_StampPDF_Call) Run(run func(ctx context.Context, file io.Reader, stamp io.Reader)) *Client_StampPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.Reader
		if args[1] != nil {
			arg1 = args[1].(io.Reader)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_StampPDF_Call) Return(n int64, readSeeker io.ReadSeeker, err error) *Client_StampPDF_Call {
	_c.Call.Return(n, readSeeker, err)
	return _c
}

func (_c *Client_StampPDF_Call) RunAndReturn(run func(ctx context.Context, file io.Reader, stamp io.Reader) (int64, io.ReadSeeker, error)) *Client_StampPDF_Call {
	_c.Call.Return(run)
	return _c
}
