// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// NewKafkaWriter creates a new instance of KafkaWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafkaWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *KafkaWriter {
	mock := &KafkaWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KafkaWriter is an autogenerated mock type for the KafkaWriter type
type KafkaWriter struct {
	mock.Mock
}

type KafkaWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *KafkaWriter) EXPECT() *KafkaWriter_Expecter {
	return &KafkaWriter_Expecter{mock: &_m.Mock}
}

// WriteMessages provides a mock function for the type KafkaWriter
func (_mock *KafkaWriter) WriteMessages(context1 context.Context, messages ...kafka.Message) error {
	// kafka.Message
	_va := make([]any, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []any
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessages")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = returnFunc(context1, messages...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KafkaWriter_WriteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessages'
type KafkaWriter_WriteMessages_Call struct {
	*mock.Call
}

// WriteMessages is a helper method to define mock.On call
//   - context1 context.Context
//   - messages ...kafka.Message
func (_e *KafkaWriter_Expecter) WriteMessages(context1 any, messages ...any) *KafkaWriter_WriteMessages_Call {
	return &KafkaWriter_WriteMessages_Call{Call: _e.mock.On("WriteMessages",
		append([]any{context1}, messages...)...)}
}

func (_c *KafkaWriter_WriteMessages_Call) Run(run func(context1 context.Context, messages ...kafka.Message)) *KafkaWriter_WriteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []kafka.Message
		variadicArgs := make([]kafka.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(kafka.Message)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *KafkaWriter_WriteMessages_Call) Return(err error) *KafkaWriter_WriteMessages_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KafkaWriter_WriteMessages_Call) RunAndReturn(run func(context1 context.Context, messages ...kafka.Message) error) *KafkaWriter_WriteMessages_Call {
	_c.Call.Return(run)
	return _c
}
