// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRegistryClient creates a new instance of RegistryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryClient {
	mock := &RegistryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RegistryClient is an autogenerated mock type for the RegistryClient type
type RegistryClient struct {
	mock.Mock
}

type RegistryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryClient) EXPECT() *RegistryClient_Expecter {
	return &RegistryClient_Expecter{mock: &_m.Mock}
}

// GetSchema provides a mock function for the type RegistryClient
func (_mock *RegistryClient) GetSchema(ctx context.Context, id int32) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSchema")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RegistryClient_GetSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSchema'
type RegistryClient_GetSchema_Call struct {
	*mock.Call
}

// GetSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *RegistryClient_Expecter) GetSchema(ctx any, id any) *RegistryClient_GetSchema_Call {
	return &RegistryClient_GetSchema_Call{Call: _e.mock.On("GetSchema", ctx, id)}
}

func (_c *RegistryClient_GetSchema_Call) Run(run func(ctx context.Context, id int32)) *RegistryClient_GetSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RegistryClient_GetSchema_Call) Return(s string, err error) *RegistryClient_GetSchema_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *RegistryClient_GetSchema_Call) RunAndReturn(run func(ctx context.Context, id int32) (string, error)) *RegistryClient_GetSchema_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterSchema provides a mock function for the type RegistryClient
func (_mock *RegistryClient) RegisterSchema(ctx context.Context, subject string, schema string) (int32, error) {
	ret := _mock.Called(ctx, subject, schema)

	if len(ret) == 0 {
		panic("no return value specified for RegisterSchema")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int32, error)); ok {
		return returnFunc(ctx, subject, schema)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int32); ok {
		r0 = returnFunc(ctx, subject, schema)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, subject, schema)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RegistryClient_RegisterSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterSchema'
type RegistryClient_RegisterSchema_Call struct {
	*mock.Call
}

// RegisterSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - schema string
func (_e *RegistryClient_Expecter) RegisterSchema(ctx any, subject any, schema any) *RegistryClient_RegisterSchema_Call {
	return &RegistryClient_RegisterSchema_Call{Call: _e.mock.On("RegisterSchema", ctx, subject, schema)}
}

func (_c *RegistryClient_RegisterSchema_Call) Run(run func(ctx context.Context, subject string, schema string)) *RegistryClient_RegisterSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RegistryClient_RegisterSchema_Call) Return(n int32, err error) *RegistryClient_RegisterSchema_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *RegistryClient_RegisterSchema_Call) RunAndReturn(run func(ctx context.Context, subject string, schema string) (int32, error)) *RegistryClient_RegisterSchema_Call {
	_c.Call.Return(run)
	return _c
}
