// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jdate"
	"github.com/Freelance-launchpad/backend-interview/services/payroll/pkg"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CancelSdtc provides a mock function for the type Client
func (_mock *Client) CancelSdtc(ctx context.Context, offerID uuid.UUID) error {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for CancelSdtc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_CancelSdtc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelSdtc'
type Client_CancelSdtc_Call struct {
	*mock.Call
}

// CancelSdtc is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) CancelSdtc(ctx any, offerID any) *Client_CancelSdtc_Call {
	return &Client_CancelSdtc_Call{Call: _e.mock.On("CancelSdtc", ctx, offerID)}
}

func (_c *Client_CancelSdtc_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_CancelSdtc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_CancelSdtc_Call) Return(err error) *Client_CancelSdtc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_CancelSdtc_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) error) *Client_CancelSdtc_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSalary provides a mock function for the type Client
func (_mock *Client) DeleteSalary(ctx context.Context, salaryID uuid.UUID) error {
	ret := _mock.Called(ctx, salaryID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSalary")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, salaryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_DeleteSalary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSalary'
type Client_DeleteSalary_Call struct {
	*mock.Call
}

// DeleteSalary is a helper method to define mock.On call
//   - ctx context.Context
//   - salaryID uuid.UUID
func (_e *Client_Expecter) DeleteSalary(ctx any, salaryID any) *Client_DeleteSalary_Call {
	return &Client_DeleteSalary_Call{Call: _e.mock.On("DeleteSalary", ctx, salaryID)}
}

func (_c *Client_DeleteSalary_Call) Run(run func(ctx context.Context, salaryID uuid.UUID)) *Client_DeleteSalary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_DeleteSalary_Call) Return(err error) *Client_DeleteSalary_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_DeleteSalary_Call) RunAndReturn(run func(ctx context.Context, salaryID uuid.UUID) error) *Client_DeleteSalary_Call {
	_c.Call.Return(run)
	return _c
}

// GetDebt provides a mock function for the type Client
func (_mock *Client) GetDebt(ctx context.Context, offerID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetDebt")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetDebt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDebt'
type Client_GetDebt_Call struct {
	*mock.Call
}

// GetDebt is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetDebt(ctx any, offerID any) *Client_GetDebt_Call {
	return &Client_GetDebt_Call{Call: _e.mock.On("GetDebt", ctx, offerID)}
}

func (_c *Client_GetDebt_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetDebt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetDebt_Call) Return(n int64, err error) *Client_GetDebt_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Client_GetDebt_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (int64, error)) *Client_GetDebt_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfferSalaries provides a mock function for the type Client
func (_mock *Client) GetOfferSalaries(ctx context.Context, offerID uuid.UUID, filters pkg.SalaryFiltersQuery) ([]pkg.SalaryResponse, int, error) {
	ret := _mock.Called(ctx, offerID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetOfferSalaries")
	}

	var r0 []pkg.SalaryResponse
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.SalaryFiltersQuery) ([]pkg.SalaryResponse, int, error)); ok {
		return returnFunc(ctx, offerID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.SalaryFiltersQuery) []pkg.SalaryResponse); ok {
		r0 = returnFunc(ctx, offerID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.SalaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, pkg.SalaryFiltersQuery) int); ok {
		r1 = returnFunc(ctx, offerID, filters)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, pkg.SalaryFiltersQuery) error); ok {
		r2 = returnFunc(ctx, offerID, filters)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Client_GetOfferSalaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfferSalaries'
type Client_GetOfferSalaries_Call struct {
	*mock.Call
}

// GetOfferSalaries is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - filters pkg.SalaryFiltersQuery
func (_e *Client_Expecter) GetOfferSalaries(ctx any, offerID any, filters any) *Client_GetOfferSalaries_Call {
	return &Client_GetOfferSalaries_Call{Call: _e.mock.On("GetOfferSalaries", ctx, offerID, filters)}
}

func (_c *Client_GetOfferSalaries_Call) Run(run func(ctx context.Context, offerID uuid.UUID, filters pkg.SalaryFiltersQuery)) *Client_GetOfferSalaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 pkg.SalaryFiltersQuery
		if args[2] != nil {
			arg2 = args[2].(pkg.SalaryFiltersQuery)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_GetOfferSalaries_Call) Return(salaryResponses []pkg.SalaryResponse, n int, err error) *Client_GetOfferSalaries_Call {
	_c.Call.Return(salaryResponses, n, err)
	return _c
}

func (_c *Client_GetOfferSalaries_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, filters pkg.SalaryFiltersQuery) ([]pkg.SalaryResponse, int, error)) *Client_GetOfferSalaries_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeverance provides a mock function for the type Client
func (_mock *Client) GetSeverance(ctx context.Context, offerID uuid.UUID) (int64, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeverance")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int64, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int64); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetSeverance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeverance'
type Client_GetSeverance_Call struct {
	*mock.Call
}

// GetSeverance is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetSeverance(ctx any, offerID any) *Client_GetSeverance_Call {
	return &Client_GetSeverance_Call{Call: _e.mock.On("GetSeverance", ctx, offerID)}
}

func (_c *Client_GetSeverance_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetSeverance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetSeverance_Call) Return(n int64, err error) *Client_GetSeverance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *Client_GetSeverance_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) (int64, error)) *Client_GetSeverance_Call {
	_c.Call.Return(run)
	return _c
}

// InitSdtc provides a mock function for the type Client
func (_mock *Client) InitSdtc(ctx context.Context, offerID uuid.UUID, churnDate jdate.Date, salaryID *uuid.UUID) error {
	ret := _mock.Called(ctx, offerID, churnDate, salaryID)

	if len(ret) == 0 {
		panic("no return value specified for InitSdtc")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, jdate.Date, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, offerID, churnDate, salaryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_InitSdtc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitSdtc'
type Client_InitSdtc_Call struct {
	*mock.Call
}

// InitSdtc is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - churnDate jdate.Date
//   - salaryID *uuid.UUID
func (_e *Client_Expecter) InitSdtc(ctx any, offerID any, churnDate any, salaryID any) *Client_InitSdtc_Call {
	return &Client_InitSdtc_Call{Call: _e.mock.On("InitSdtc", ctx, offerID, churnDate, salaryID)}
}

func (_c *Client_InitSdtc_Call) Run(run func(ctx context.Context, offerID uuid.UUID, churnDate jdate.Date, salaryID *uuid.UUID)) *Client_InitSdtc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 jdate.Date
		if args[2] != nil {
			arg2 = args[2].(jdate.Date)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Client_InitSdtc_Call) Return(err error) *Client_InitSdtc_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_InitSdtc_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, churnDate jdate.Date, salaryID *uuid.UUID) error) *Client_InitSdtc_Call {
	_c.Call.Return(run)
	return _c
}

// RecomputeSalaryRules provides a mock function for the type Client
func (_mock *Client) RecomputeSalaryRules(ctx context.Context, salaryID uuid.UUID) error {
	ret := _mock.Called(ctx, salaryID)

	if len(ret) == 0 {
		panic("no return value specified for RecomputeSalaryRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, salaryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_RecomputeSalaryRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecomputeSalaryRules'
type Client_RecomputeSalaryRules_Call struct {
	*mock.Call
}

// RecomputeSalaryRules is a helper method to define mock.On call
//   - ctx context.Context
//   - salaryID uuid.UUID
func (_e *Client_Expecter) RecomputeSalaryRules(ctx any, salaryID any) *Client_RecomputeSalaryRules_Call {
	return &Client_RecomputeSalaryRules_Call{Call: _e.mock.On("RecomputeSalaryRules", ctx, salaryID)}
}

func (_c *Client_RecomputeSalaryRules_Call) Run(run func(ctx context.Context, salaryID uuid.UUID)) *Client_RecomputeSalaryRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_RecomputeSalaryRules_Call) Return(err error) *Client_RecomputeSalaryRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_RecomputeSalaryRules_Call) RunAndReturn(run func(ctx context.Context, salaryID uuid.UUID) error) *Client_RecomputeSalaryRules_Call {
	_c.Call.Return(run)
	return _c
}

// SimulateSalary provides a mock function for the type Client
func (_mock *Client) SimulateSalary(ctx context.Context, offerID uuid.UUID, input pkg.SimulationData) (pkg.SimulationResult, error) {
	ret := _mock.Called(ctx, offerID, input)

	if len(ret) == 0 {
		panic("no return value specified for SimulateSalary")
	}

	var r0 pkg.SimulationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.SimulationData) (pkg.SimulationResult, error)); ok {
		return returnFunc(ctx, offerID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, pkg.SimulationData) pkg.SimulationResult); ok {
		r0 = returnFunc(ctx, offerID, input)
	} else {
		r0 = ret.Get(0).(pkg.SimulationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, pkg.SimulationData) error); ok {
		r1 = returnFunc(ctx, offerID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_SimulateSalary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulateSalary'
type Client_SimulateSalary_Call struct {
	*mock.Call
}

// SimulateSalary is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - input pkg.SimulationData
func (_e *Client_Expecter) SimulateSalary(ctx any, offerID any, input any) *Client_SimulateSalary_Call {
	return &Client_SimulateSalary_Call{Call: _e.mock.On("SimulateSalary", ctx, offerID, input)}
}

func (_c *Client_SimulateSalary_Call) Run(run func(ctx context.Context, offerID uuid.UUID, input pkg.SimulationData)) *Client_SimulateSalary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 pkg.SimulationData
		if args[2] != nil {
			arg2 = args[2].(pkg.SimulationData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_SimulateSalary_Call) Return(simulationResult pkg.SimulationResult, err error) *Client_SimulateSalary_Call {
	_c.Call.Return(simulationResult, err)
	return _c
}

func (_c *Client_SimulateSalary_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, input pkg.SimulationData) (pkg.SimulationResult, error)) *Client_SimulateSalary_Call {
	_c.Call.Return(run)
	return _c
}
