// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package oauth

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jdb"
	mock "github.com/stretchr/testify/mock"
)

// NewStoreMock creates a new instance of StoreMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStoreMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StoreMock {
	mock := &StoreMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StoreMock is an autogenerated mock type for the Store type
type StoreMock struct {
	mock.Mock
}

type StoreMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StoreMock) EXPECT() *StoreMock_Expecter {
	return &StoreMock_Expecter{mock: &_m.Mock}
}

// BeginLocked provides a mock function for the type StoreMock
func (_mock *StoreMock) BeginLocked(ctx context.Context) (jdb.RunnerTx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginLocked")
	}

	var r0 jdb.RunnerTx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (jdb.RunnerTx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) jdb.RunnerTx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jdb.RunnerTx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_BeginLocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginLocked'
type StoreMock_BeginLocked_Call struct {
	*mock.Call
}

// BeginLocked is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StoreMock_Expecter) BeginLocked(ctx any) *StoreMock_BeginLocked_Call {
	return &StoreMock_BeginLocked_Call{Call: _e.mock.On("BeginLocked", ctx)}
}

func (_c *StoreMock_BeginLocked_Call) Run(run func(ctx context.Context)) *StoreMock_BeginLocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StoreMock_BeginLocked_Call) Return(runnerTx jdb.RunnerTx, err error) *StoreMock_BeginLocked_Call {
	_c.Call.Return(runnerTx, err)
	return _c
}

func (_c *StoreMock_BeginLocked_Call) RunAndReturn(run func(ctx context.Context) (jdb.RunnerTx, error)) *StoreMock_BeginLocked_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function for the type StoreMock
func (_mock *StoreMock) GetToken(ctx context.Context, tx jdb.Runner, tokenName string) (Token, error) {
	ret := _mock.Called(ctx, tx, tokenName)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jdb.Runner, string) (Token, error)); ok {
		return returnFunc(ctx, tx, tokenName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jdb.Runner, string) Token); ok {
		r0 = returnFunc(ctx, tx, tokenName)
	} else {
		r0 = ret.Get(0).(Token)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jdb.Runner, string) error); ok {
		r1 = returnFunc(ctx, tx, tokenName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StoreMock_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type StoreMock_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tx jdb.Runner
//   - tokenName string
func (_e *StoreMock_Expecter) GetToken(ctx any, tx any, tokenName any) *StoreMock_GetToken_Call {
	return &StoreMock_GetToken_Call{Call: _e.mock.On("GetToken", ctx, tx, tokenName)}
}

func (_c *StoreMock_GetToken_Call) Run(run func(ctx context.Context, tx jdb.Runner, tokenName string)) *StoreMock_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jdb.Runner
		if args[1] != nil {
			arg1 = args[1].(jdb.Runner)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StoreMock_GetToken_Call) Return(token Token, err error) *StoreMock_GetToken_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *StoreMock_GetToken_Call) RunAndReturn(run func(ctx context.Context, tx jdb.Runner, tokenName string) (Token, error)) *StoreMock_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateToken provides a mock function for the type StoreMock
func (_mock *StoreMock) UpdateToken(ctx context.Context, tx jdb.Runner, token Token) error {
	ret := _mock.Called(ctx, tx, token)

	if len(ret) == 0 {
		panic("no return value specified for UpdateToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jdb.Runner, Token) error); ok {
		r0 = returnFunc(ctx, tx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StoreMock_UpdateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateToken'
type StoreMock_UpdateToken_Call struct {
	*mock.Call
}

// UpdateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tx jdb.Runner
//   - token Token
func (_e *StoreMock_Expecter) UpdateToken(ctx any, tx any, token any) *StoreMock_UpdateToken_Call {
	return &StoreMock_UpdateToken_Call{Call: _e.mock.On("UpdateToken", ctx, tx, token)}
}

func (_c *StoreMock_UpdateToken_Call) Run(run func(ctx context.Context, tx jdb.Runner, token Token)) *StoreMock_UpdateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jdb.Runner
		if args[1] != nil {
			arg1 = args[1].(jdb.Runner)
		}
		var arg2 Token
		if args[2] != nil {
			arg2 = args[2].(Token)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StoreMock_UpdateToken_Call) Return(err error) *StoreMock_UpdateToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StoreMock_UpdateToken_Call) RunAndReturn(run func(ctx context.Context, tx jdb.Runner, token Token) error) *StoreMock_UpdateToken_Call {
	_c.Call.Return(run)
	return _c
}
