// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/common/jkafka"
	mock "github.com/stretchr/testify/mock"
)

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// RegisterSchema provides a mock function for the type Producer
func (_mock *Producer) RegisterSchema(ctx context.Context, schema string) error {
	ret := _mock.Called(ctx, schema)

	if len(ret) == 0 {
		panic("no return value specified for RegisterSchema")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, schema)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_RegisterSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterSchema'
type Producer_RegisterSchema_Call struct {
	*mock.Call
}

// RegisterSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - schema string
func (_e *Producer_Expecter) RegisterSchema(ctx any, schema any) *Producer_RegisterSchema_Call {
	return &Producer_RegisterSchema_Call{Call: _e.mock.On("RegisterSchema", ctx, schema)}
}

func (_c *Producer_RegisterSchema_Call) Run(run func(ctx context.Context, schema string)) *Producer_RegisterSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Producer_RegisterSchema_Call) Return(err error) *Producer_RegisterSchema_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_RegisterSchema_Call) RunAndReturn(run func(ctx context.Context, schema string) error) *Producer_RegisterSchema_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type Producer
func (_mock *Producer) Write(ctx context.Context, message jkafka.Message) error {
	ret := _mock.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jkafka.Message) error); ok {
		r0 = returnFunc(ctx, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type Producer_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - message jkafka.Message
func (_e *Producer_Expecter) Write(ctx any, message any) *Producer_Write_Call {
	return &Producer_Write_Call{Call: _e.mock.On("Write", ctx, message)}
}

func (_c *Producer_Write_Call) Run(run func(ctx context.Context, message jkafka.Message)) *Producer_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jkafka.Message
		if args[1] != nil {
			arg1 = args[1].(jkafka.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Producer_Write_Call) Return(err error) *Producer_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Write_Call) RunAndReturn(run func(ctx context.Context, message jkafka.Message) error) *Producer_Write_Call {
	_c.Call.Return(run)
	return _c
}
