package jutils

import "slices"

var europeanUnionMembersCountryCodes = []string{
	"AT",
	"BE",
	"BG",
	"CY",
	"CZ",
	"DE",
	"DK",
	"EE",
	"ES",
	"FI",
	"FR",
	"GR",
	"HR",
	"HU",
	"IE",
	"IT",
	"LT",
	"LU",
	"LV",
	"MT",
	"NL",
	"PL",
	"PT",
	"RO",
	"SE",
	"SI",
	"SK",
}

func IsCountryEuropeanMember(code string) bool {
	return slices.Contains(europeanUnionMembersCountryCodes, code)
}

var allFrenchCountryCodes = []string{
	"FR", // France
	"GP", // Guadeloupe
	"MQ", // Martinique
	"RE", // Réunion
	"GF", // Guyane Francaise
	"YT", // Mayotte
	"MF", // Saint-Martin, partie francaise
	"BL", // Saint-Barthelemy
	"PM", // Saint-Pierre-et-Miquelon
	"PF", // Polynésie française
	"WF", // Wallis-et-Futuna
	"NC", // Nouvelle-Calédonie
}

func IsCountryFrenchMember(code string) bool {
	return slices.Contains(allFrenchCountryCodes, code)
}

var allFrenchLiableVATCountryCodes = []string{
	"FR",
	"MQ",
	"GP",
	"RE",
}

func IsCountryFrenchVATLiable(code string) bool {
	return slices.Contains(allFrenchLiableVATCountryCodes, code)
}

func IsCountryLiableVAT(code string) bool {
	return code == "MC" || IsCountryFrenchVATLiable(code) || IsCountryEuropeanMember(code)
}

var alpha3ToAlpha2 = map[string]string{
	"ABW": "AW",
	"AFG": "AF",
	"AGO": "AO",
	"AIA": "AI",
	"ALA": "AX",
	"ALB": "AL",
	"AND": "AD",
	"ARE": "AE",
	"ARG": "AR",
	"ARM": "AM",
	"ASM": "AS",
	"ATA": "AQ",
	"ATF": "TF",
	"ATG": "AG",
	"AUS": "AU",
	"AUT": "AT",
	"AZE": "AZ",
	"BDI": "BI",
	"BEL": "BE",
	"BEN": "BJ",
	"BES": "BQ",
	"BFA": "BF",
	"BGD": "BD",
	"BGR": "BG",
	"BHR": "BH",
	"BHS": "BS",
	"BIH": "BA",
	"BLM": "BL",
	"BLR": "BY",
	"BLZ": "BZ",
	"BMU": "BM",
	"BOL": "BO",
	"BRA": "BR",
	"BRB": "BB",
	"BRN": "BN",
	"BTN": "BT",
	"BVT": "BV",
	"BWA": "BW",
	"CAF": "CF",
	"CAN": "CA",
	"CCK": "CC",
	"CHE": "CH",
	"CHL": "CL",
	"CHN": "CN",
	"CIV": "CI",
	"CMR": "CM",
	"COD": "CD",
	"COG": "CG",
	"COK": "CK",
	"COL": "CO",
	"COM": "KM",
	"CPV": "CV",
	"CRI": "CR",
	"CUB": "CU",
	"CUW": "CW",
	"CXR": "CX",
	"CYM": "KY",
	"CYP": "CY",
	"CZE": "CZ",
	"DEU": "DE",
	"DJI": "DJ",
	"DMA": "DM",
	"DNK": "DK",
	"DOM": "DO",
	"DZA": "DZ",
	"ECU": "EC",
	"EGY": "EG",
	"ERI": "ER",
	"ESH": "EH",
	"ESP": "ES",
	"EST": "EE",
	"ETH": "ET",
	"FIN": "FI",
	"FJI": "FJ",
	"FLK": "FK",
	"FRA": "FR",
	"FRO": "FO",
	"FSM": "FM",
	"GAB": "GA",
	"GBR": "GB",
	"GEO": "GE",
	"GGY": "GG",
	"GHA": "GH",
	"GIB": "GI",
	"GIN": "GN",
	"GLP": "GP",
	"GMB": "GM",
	"GNB": "GW",
	"GNQ": "GQ",
	"GRC": "GR",
	"GRD": "GD",
	"GRL": "GL",
	"GTM": "GT",
	"GUF": "GF",
	"GUM": "GU",
	"GUY": "GY",
	"HKG": "HK",
	"HMD": "HM",
	"HND": "HN",
	"HRV": "HR",
	"HTI": "HT",
	"HUN": "HU",
	"IDN": "ID",
	"IMN": "IM",
	"IND": "IN",
	"IOT": "IO",
	"IRL": "IE",
	"IRN": "IR",
	"IRQ": "IQ",
	"ISL": "IS",
	"ISR": "IL",
	"ITA": "IT",
	"JAM": "JM",
	"JEY": "JE",
	"JOR": "JO",
	"JPN": "JP",
	"KAZ": "KZ",
	"KEN": "KE",
	"KGZ": "KG",
	"KHM": "KH",
	"KIR": "KI",
	"KNA": "KN",
	"KOR": "KR",
	"KWT": "KW",
	"LAO": "LA",
	"LBN": "LB",
	"LBR": "LR",
	"LBY": "LY",
	"LCA": "LC",
	"LIE": "LI",
	"LKA": "LK",
	"LSO": "LS",
	"LTU": "LT",
	"LUX": "LU",
	"LVA": "LV",
	"MAC": "MO",
	"MAF": "MF",
	"MAR": "MA",
	"MCO": "MC",
	"MDA": "MD",
	"MDG": "MG",
	"MDV": "MV",
	"MEX": "MX",
	"MHL": "MH",
	"MKD": "MK",
	"MLI": "ML",
	"MLT": "MT",
	"MMR": "MM",
	"MNE": "ME",
	"MNG": "MN",
	"MNP": "MP",
	"MOZ": "MZ",
	"MRT": "MR",
	"MSR": "MS",
	"MTQ": "MQ",
	"MUS": "MU",
	"MWI": "MW",
	"MYS": "MY",
	"MYT": "YT",
	"NAM": "NA",
	"NCL": "NC",
	"NER": "NE",
	"NFK": "NF",
	"NGA": "NG",
	"NIC": "NI",
	"NIU": "NU",
	"NLD": "NL",
	"NOR": "NO",
	"NPL": "NP",
	"NRU": "NR",
	"NZL": "NZ",
	"OMN": "OM",
	"PAK": "PK",
	"PAN": "PA",
	"PCN": "PN",
	"PER": "PE",
	"PHL": "PH",
	"PLW": "PW",
	"PNG": "PG",
	"POL": "PL",
	"PRI": "PR",
	"PRK": "KP",
	"PRT": "PT",
	"PRY": "PY",
	"PSE": "PS",
	"PYF": "PF",
	"QAT": "QA",
	"REU": "RE",
	"ROU": "RO",
	"RUS": "RU",
	"RWA": "RW",
	"SAU": "SA",
	"SDN": "SD",
	"SEN": "SN",
	"SGP": "SG",
	"SGS": "GS",
	"SHN": "SH",
	"SJM": "SJ",
	"SLB": "SB",
	"SLE": "SL",
	"SLV": "SV",
	"SMR": "SM",
	"SOM": "SO",
	"SPM": "PM",
	"SRB": "RS",
	"SSD": "SS",
	"STP": "ST",
	"SUR": "SR",
	"SVK": "SK",
	"SVN": "SI",
	"SWE": "SE",
	"SWZ": "SZ",
	"SXM": "SX",
	"SYC": "SC",
	"SYR": "SY",
	"TCA": "TC",
	"TCD": "TD",
	"TGO": "TG",
	"THA": "TH",
	"TJK": "TJ",
	"TKL": "TK",
	"TKM": "TM",
	"TLS": "TL",
	"TON": "TO",
	"TTO": "TT",
	"TUN": "TN",
	"TUR": "TR",
	"TUV": "TV",
	"TWN": "TW",
	"TZA": "TZ",
	"UGA": "UG",
	"UKR": "UA",
	"UMI": "UM",
	"URY": "UY",
	"USA": "US",
	"UZB": "UZ",
	"VAT": "VA",
	"VCT": "VC",
	"VEN": "VE",
	"VGB": "VG",
	"VIR": "VI",
	"VNM": "VN",
	"VUT": "VU",
	"WLF": "WF",
	"WSM": "WS",
	"XKX": "XK",
	"YEM": "YE",
	"ZAF": "ZA",
	"ZMB": "ZM",
	"ZWE": "ZW",
}

var alpha2ToName = map[string]string{
	"AD": "ANDORRE",
	"AE": "EMIRATS ARABES UNIS",
	"AF": "AFGHANISTAN",
	"AG": "ANTIGUA-ET-BARBUDA",
	"AI": "ANGUILLA",
	"AL": "ALBANIE",
	"AM": "ARMENIE",
	"AN": "ANTILLES NEERLANDAISES",
	"AO": "ANGOLA",
	"AQ": "ANTARCTIQUE",
	"AR": "ARGENTINE",
	"AS": "SAMOA AMERICAINES",
	"AT": "AUTRICHE",
	"AU": "AUSTRALIE",
	"AW": "ARUBA",
	"AX": "ALAND ILES",
	"AZ": "AZERBAIJAN",
	"BA": "BOSNIE-HERZEGOVINE",
	"BB": "BARBADE",
	"BD": "BANGLADESH",
	"BE": "BELGIQUE",
	"BF": "BURKINA FASO",
	"BG": "BULGARIE",
	"BH": "BAHREIN",
	"BI": "BURUNDI",
	"BJ": "BENIN",
	"BL": "SAINT-BARTHELEMY",
	"BM": "BERMUDES",
	"BN": "BRUNEI DARUSSALAM",
	"BO": "BOLIVIA l'ETAT PLURINATIONAL DE",
	"BR": "BRESIL",
	"BS": "BAHAMAS",
	"BT": "BHOUTAN",
	"BV": "BOUVET ILE",
	"BW": "BOTSWANA",
	"BY": "BELARUS",
	"BZ": "BELIZE",
	"CA": "CANADA",
	"CC": "COCOS KEELING ILES",
	"CD": "CONGO LA REPUBLIQUE DEMOCRATIQUE DU",
	"CF": "CENTRAFRICAINE REPUBLIQUE",
	"CG": "CONGO",
	"CH": "SUISSE",
	"CI": "COTE D'IVOIRE",
	"CK": "COOK ILES",
	"CL": "CHILI",
	"CM": "CAMEROUN",
	"CN": "CHINE",
	"CO": "COLOMBIE",
	"CR": "COSTA RICA",
	"CU": "CUBA",
	"CV": "CAP-VERT",
	"CW": "CURACAO",
	"CX": "CHRISTMAS ILE",
	"CY": "CHYPRE",
	"CZ": "TCHEQUE REPUBLIQUE",
	"DE": "ALLEMAGNE",
	"DJ": "DJIBOUTI",
	"DK": "DANEMARK",
	"DM": "DOMINIQUE",
	"DO": "DOMINICAINE REPUBLIQUE",
	"DZ": "ALGERIE",
	"EC": "EQUATEUR",
	"EE": "ESTONIE",
	"EG": "EGYPTE",
	"EH": "SAHARA OCCIDENTAL",
	"ER": "ERYTHREE",
	"ES": "ESPAGNE",
	"ET": "ETHIOPIE",
	"FI": "FINLANDE",
	"FJ": "FIDJI",
	"FK": "FALKLAND ILES (MALVINAS)",
	"FM": "MICRONESIE ETATS FEDERES DE",
	"FO": "FEROE ILES",
	"FR": "FRANCE",
	"GA": "GABON",
	"GB": "ROYAUME-UNI",
	"GD": "GRENADE",
	"GE": "GEORGIAE",
	"GF": "GUYANE FRANCAISE",
	"GG": "GUERNESEY",
	"GH": "GHANA",
	"GI": "GIBRALTAR",
	"GL": "GROENLAND",
	"GM": "GAMBIE",
	"GN": "GUINEE",
	"GP": "GUADELOUPE",
	"GQ": "GUINEE EQUATORIALE",
	"GR": "GRECE",
	"GS": "GEORGIE DU SUD ET LES ILES SANDWICH DU SUD",
	"GT": "GUATEMALA",
	"GU": "GUAM",
	"GW": "GUINEE-BISSAU",
	"GY": "GUYANA",
	"HK": "HONG-KONG",
	"HM": "HEARD ILE ET MCDONALD ILES",
	"HN": "HONDURAS",
	"HR": "CROATIE",
	"HT": "HAITI",
	"HU": "HONGRIE",
	"ID": "INDONESIE",
	"IE": "IRLANDE",
	"IL": "ISRAËL",
	"IM": "ILE OF MAN",
	"IN": "INDE",
	"IO": "OCEAN INDIEN TERRITOIRE BRITANNIQUE DE L'",
	"IQ": "IRAQ",
	"IR": "IRAN REPUBLIQUE ISLAMIQUE D'",
	"IS": "ISLANDE",
	"IT": "ITALIE",
	"JE": "JERSEY",
	"JM": "JAMAIQUE",
	"JO": "JORDANIE",
	"JP": "JAPON",
	"KE": "KENYA",
	"KG": "KIRGHIZISTAN",
	"KH": "CAMBODGE",
	"KI": "KIRIBATI",
	"KM": "COMORES",
	"KN": "SAINT-KITTS-ET_NEVIS",
	"KP": "COREE REPUBLIQUE POPULAIRE DEMOCRATIQUE DE",
	"KR": "COREE REPUBLIQUE DE",
	"KW": "KOWEIT",
	"KY": "CAIMANES ILES",
	"KZ": "KAZAKHSTAN",
	"LA": "LAOS REPUBLIQUE DEMOCRATIQUE POPULAIRE",
	"LB": "LIBAN",
	"LC": "SAINTE-LUCIE",
	"LI": "LIECHTENSTEIN",
	"LK": "SRI LANKA",
	"LR": "LIBERIA",
	"LS": "LESOTHO",
	"LT": "LITUANIE",
	"LU": "LUXEMBOURG",
	"LV": "LETTONIE",
	"LY": "LIBYE",
	"MA": "MAROC",
	"MC": "MONACO",
	"MD": "MOLDOVA REPUBLIQUE DE",
	"ME": "MONTENEGRO",
	"MF": "SAINT-MARTIN",
	"MG": "MADAGASCAR",
	"MH": "MARSHALL ILES",
	"MK": "MACEDOINE DU NORD",
	"ML": "MALI",
	"MM": "MYANMAR",
	"MN": "MONGOLIE",
	"MO": "MACAO",
	"MP": "MARIANNES DU NORD ILES",
	"MQ": "MARTINIQUE",
	"MR": "MAURITANIE",
	"MS": "MONTSERRAT",
	"MT": "MALTE",
	"MU": "MAURICE",
	"MV": "MALDIVES",
	"MW": "MALAWI",
	"MX": "MEXIQUE",
	"MY": "MALAISIE",
	"MZ": "MOZAMBIQUE",
	"NA": "NAMIBIE",
	"NC": "NOUVELLE CALEDONIE",
	"NE": "NIGER",
	"NF": "NORFOLK ILE",
	"NG": "NIGERIA",
	"NI": "NICARAGUA",
	"NL": "PAYS-BAS",
	"NO": "NORVEGE",
	"NP": "NEPAL",
	"NR": "NAURU",
	"NU": "NIUE",
	"NZ": "NOUVELLE-ZELANDE",
	"OM": "OMAN",
	"PA": "PANAMA",
	"PE": "PEROU",
	"PF": "POLYNESIE FRANÇAISE",
	"PG": "PAPOUASIE NOUVELLE GUINEE",
	"PH": "PHILIPPINES",
	"PK": "PAKISTAN",
	"PL": "POLOGNE",
	"PM": "SAINT-PIERRE-ET-MIQUELON",
	"PN": "PITCAIRN",
	"PR": "PORTO RICO",
	"PS": "PALESTINE ETAT DE",
	"PT": "PORTUGAL",
	"PW": "PALAOS",
	"PY": "PARAGUAY",
	"QA": "QATAR",
	"RE": "REUNION",
	"RO": "ROUMANIE",
	"RS": "SERBIE",
	"RU": "RUSSIE FEDERATION DE",
	"RW": "RWANDA",
	"SA": "ARABIE SAOUDITE",
	"SB": "SALOMON ILES",
	"SC": "SEYCHELLES",
	"SD": "SOUDAN",
	"SE": "SUEDE",
	"SG": "SINGAPOUR",
	"SH": "SAINTE-HELENE",
	"SI": "SLOVENIE",
	"SJ": "SVALBARD ET ILE JAN MAYEN",
	"SK": "SLOVAQUIE",
	"SL": "SIERRA LEONE",
	"SM": "SAINT-MARIN",
	"SN": "SENEGAL",
	"SO": "SOMALIE",
	"SR": "SURINAME",
	"ST": "SAO TOME-ET-PRINCIPE",
	"SV": "EL SALVADOR",
	"SY": "SYRIENNE REPUBLIQUE ARABE",
	"SZ": "ESWATINI",
	"TC": "TURKS ET CAIQUES ILES",
	"TD": "TCHAD",
	"TF": "TERRES AUSTRALES FRANCAISES",
	"TG": "TOGO",
	"TH": "THAILANDE",
	"TJ": "TADJIKISTAN",
	"TK": "TOKELAU",
	"TL": "TIMOR-LESTE",
	"TM": "TURKMENISTAN",
	"TN": "TUNISIE",
	"TO": "TONGA",
	"TR": "TURQUIE",
	"TT": "TRINITE-ET-TOBAGO",
	"TV": "TUVALU",
	"TW": "TAIWAN PROVINCE DE CHINE",
	"TZ": "TANZANIE REPUBLIQUE-UNIE DE",
	"UA": "UKRAINE",
	"UG": "OUGANDA",
	"UM": "ILES MINEURES ELOIGNEES DES ETATS-UNIS",
	"US": "ETATS-UNIS",
	"UY": "URUGUAY",
	"UZ": "OUZBEKISTAN",
	"VA": "SAINT-SIEGE ETAT DE LA CITE DU VATICAN",
	"VC": "SAINT-VINCENT-ET-LES GRENADINES",
	"VE": "VENEZUELA REPUBLIQUE BOLIVARIENNE DU",
	"VG": "ILES VIERGES BRITANNIQUES",
	"VI": "ILES VIERGES DES ETATS-UNIS",
	"VN": "VIET NAM",
	"VU": "VANUATU",
	"WF": "WALLIS ET FUTUNA",
	"WS": "SAMOA",
	"XK": "KOSOVO",
	"YE": "YEMEN",
	"YT": "MAYOTTE",
	"ZA": "AFRIQUE DU SUD",
	"ZM": "ZAMBIE",
	"ZW": "ZIMBABWE",
}

func CountryCodesAlpha3ToAlpha2(code string) string {
	return alpha3ToAlpha2[code]
}

func CountryCodesAlpha2ToName(code string) string {
	return alpha2ToName[code]
}
