// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Freelance-launchpad/backend-interview/services/expenses/pkg"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// CompleteAndUnlockExpenses provides a mock function for the type Client
func (_mock *Client) CompleteAndUnlockExpenses(ctx context.Context, offerID uuid.UUID, expenses []pkg.RefundedExpense) error {
	ret := _mock.Called(ctx, offerID, expenses)

	if len(ret) == 0 {
		panic("no return value specified for CompleteAndUnlockExpenses")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []pkg.RefundedExpense) error); ok {
		r0 = returnFunc(ctx, offerID, expenses)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_CompleteAndUnlockExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteAndUnlockExpenses'
type Client_CompleteAndUnlockExpenses_Call struct {
	*mock.Call
}

// CompleteAndUnlockExpenses is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - expenses []pkg.RefundedExpense
func (_e *Client_Expecter) CompleteAndUnlockExpenses(ctx any, offerID any, expenses any) *Client_CompleteAndUnlockExpenses_Call {
	return &Client_CompleteAndUnlockExpenses_Call{Call: _e.mock.On("CompleteAndUnlockExpenses", ctx, offerID, expenses)}
}

func (_c *Client_CompleteAndUnlockExpenses_Call) Run(run func(ctx context.Context, offerID uuid.UUID, expenses []pkg.RefundedExpense)) *Client_CompleteAndUnlockExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []pkg.RefundedExpense
		if args[2] != nil {
			arg2 = args[2].([]pkg.RefundedExpense)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_CompleteAndUnlockExpenses_Call) Return(err error) *Client_CompleteAndUnlockExpenses_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_CompleteAndUnlockExpenses_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, expenses []pkg.RefundedExpense) error) *Client_CompleteAndUnlockExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// GetSalaryExpenses provides a mock function for the type Client
func (_mock *Client) GetSalaryExpenses(ctx context.Context, offerID uuid.UUID) ([]pkg.SalaryExpense, error) {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSalaryExpenses")
	}

	var r0 []pkg.SalaryExpense
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]pkg.SalaryExpense, error)); ok {
		return returnFunc(ctx, offerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []pkg.SalaryExpense); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.SalaryExpense)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, offerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_GetSalaryExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSalaryExpenses'
type Client_GetSalaryExpenses_Call struct {
	*mock.Call
}

// GetSalaryExpenses is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) GetSalaryExpenses(ctx any, offerID any) *Client_GetSalaryExpenses_Call {
	return &Client_GetSalaryExpenses_Call{Call: _e.mock.On("GetSalaryExpenses", ctx, offerID)}
}

func (_c *Client_GetSalaryExpenses_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_GetSalaryExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_GetSalaryExpenses_Call) Return(salaryExpenses []pkg.SalaryExpense, err error) *Client_GetSalaryExpenses_Call {
	_c.Call.Return(salaryExpenses, err)
	return _c
}

func (_c *Client_GetSalaryExpenses_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) ([]pkg.SalaryExpense, error)) *Client_GetSalaryExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type Client
func (_mock *Client) ListCategories(ctx context.Context) ([]pkg.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []pkg.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]pkg.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []pkg.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type Client_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Client_Expecter) ListCategories(ctx any) *Client_ListCategories_Call {
	return &Client_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *Client_ListCategories_Call) Run(run func(ctx context.Context)) *Client_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Client_ListCategories_Call) Return(categorys []pkg.Category, err error) *Client_ListCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *Client_ListCategories_Call) RunAndReturn(run func(ctx context.Context) ([]pkg.Category, error)) *Client_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpenses provides a mock function for the type Client
func (_mock *Client) ListExpenses(ctx context.Context, filter pkg.ExpenseFilter, withAttachments bool) (pkg.ListExpensesResponse, error) {
	ret := _mock.Called(ctx, filter, withAttachments)

	if len(ret) == 0 {
		panic("no return value specified for ListExpenses")
	}

	var r0 pkg.ListExpensesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkg.ExpenseFilter, bool) (pkg.ListExpensesResponse, error)); ok {
		return returnFunc(ctx, filter, withAttachments)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pkg.ExpenseFilter, bool) pkg.ListExpensesResponse); ok {
		r0 = returnFunc(ctx, filter, withAttachments)
	} else {
		r0 = ret.Get(0).(pkg.ListExpensesResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pkg.ExpenseFilter, bool) error); ok {
		r1 = returnFunc(ctx, filter, withAttachments)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Client_ListExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpenses'
type Client_ListExpenses_Call struct {
	*mock.Call
}

// ListExpenses is a helper method to define mock.On call
//   - ctx context.Context
//   - filter pkg.ExpenseFilter
//   - withAttachments bool
func (_e *Client_Expecter) ListExpenses(ctx any, filter any, withAttachments any) *Client_ListExpenses_Call {
	return &Client_ListExpenses_Call{Call: _e.mock.On("ListExpenses", ctx, filter, withAttachments)}
}

func (_c *Client_ListExpenses_Call) Run(run func(ctx context.Context, filter pkg.ExpenseFilter, withAttachments bool)) *Client_ListExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pkg.ExpenseFilter
		if args[1] != nil {
			arg1 = args[1].(pkg.ExpenseFilter)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_ListExpenses_Call) Return(listExpensesResponse pkg.ListExpensesResponse, err error) *Client_ListExpenses_Call {
	_c.Call.Return(listExpensesResponse, err)
	return _c
}

func (_c *Client_ListExpenses_Call) RunAndReturn(run func(ctx context.Context, filter pkg.ExpenseFilter, withAttachments bool) (pkg.ListExpensesResponse, error)) *Client_ListExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// LockExpenses provides a mock function for the type Client
func (_mock *Client) LockExpenses(ctx context.Context, offerID uuid.UUID, expensesIDs uuid.UUIDs) error {
	ret := _mock.Called(ctx, offerID, expensesIDs)

	if len(ret) == 0 {
		panic("no return value specified for LockExpenses")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUIDs) error); ok {
		r0 = returnFunc(ctx, offerID, expensesIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_LockExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockExpenses'
type Client_LockExpenses_Call struct {
	*mock.Call
}

// LockExpenses is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
//   - expensesIDs uuid.UUIDs
func (_e *Client_Expecter) LockExpenses(ctx any, offerID any, expensesIDs any) *Client_LockExpenses_Call {
	return &Client_LockExpenses_Call{Call: _e.mock.On("LockExpenses", ctx, offerID, expensesIDs)}
}

func (_c *Client_LockExpenses_Call) Run(run func(ctx context.Context, offerID uuid.UUID, expensesIDs uuid.UUIDs)) *Client_LockExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUIDs
		if args[2] != nil {
			arg2 = args[2].(uuid.UUIDs)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Client_LockExpenses_Call) Return(err error) *Client_LockExpenses_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_LockExpenses_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID, expensesIDs uuid.UUIDs) error) *Client_LockExpenses_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpensesNonRefundable provides a mock function for the type Client
func (_mock *Client) SetExpensesNonRefundable(ctx context.Context, params []pkg.NonRefundableParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SetExpensesNonRefundable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []pkg.NonRefundableParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_SetExpensesNonRefundable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpensesNonRefundable'
type Client_SetExpensesNonRefundable_Call struct {
	*mock.Call
}

// SetExpensesNonRefundable is a helper method to define mock.On call
//   - ctx context.Context
//   - params []pkg.NonRefundableParams
func (_e *Client_Expecter) SetExpensesNonRefundable(ctx any, params any) *Client_SetExpensesNonRefundable_Call {
	return &Client_SetExpensesNonRefundable_Call{Call: _e.mock.On("SetExpensesNonRefundable", ctx, params)}
}

func (_c *Client_SetExpensesNonRefundable_Call) Run(run func(ctx context.Context, params []pkg.NonRefundableParams)) *Client_SetExpensesNonRefundable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []pkg.NonRefundableParams
		if args[1] != nil {
			arg1 = args[1].([]pkg.NonRefundableParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_SetExpensesNonRefundable_Call) Return(err error) *Client_SetExpensesNonRefundable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_SetExpensesNonRefundable_Call) RunAndReturn(run func(ctx context.Context, params []pkg.NonRefundableParams) error) *Client_SetExpensesNonRefundable_Call {
	_c.Call.Return(run)
	return _c
}

// UnlockExpenses provides a mock function for the type Client
func (_mock *Client) UnlockExpenses(ctx context.Context, offerID uuid.UUID) error {
	ret := _mock.Called(ctx, offerID)

	if len(ret) == 0 {
		panic("no return value specified for UnlockExpenses")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, offerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_UnlockExpenses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlockExpenses'
type Client_UnlockExpenses_Call struct {
	*mock.Call
}

// UnlockExpenses is a helper method to define mock.On call
//   - ctx context.Context
//   - offerID uuid.UUID
func (_e *Client_Expecter) UnlockExpenses(ctx any, offerID any) *Client_UnlockExpenses_Call {
	return &Client_UnlockExpenses_Call{Call: _e.mock.On("UnlockExpenses", ctx, offerID)}
}

func (_c *Client_UnlockExpenses_Call) Run(run func(ctx context.Context, offerID uuid.UUID)) *Client_UnlockExpenses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_UnlockExpenses_Call) Return(err error) *Client_UnlockExpenses_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_UnlockExpenses_Call) RunAndReturn(run func(ctx context.Context, offerID uuid.UUID) error) *Client_UnlockExpenses_Call {
	_c.Call.Return(run)
	return _c
}
